use crate::SimIo;

/// Export digital inputs/outputs to a minimal VCD waveform string.
///
/// - Timescale is fixed to `1ms`.
/// - Timestamps are `tick * tick_ms`.
/// - Signals are named `di<N>` and `do<N>`.
pub fn export_vcd_digital(io: &SimIo, tick_ms: u64) -> String {
    let num_di = io.num_digital_inputs();
    let num_do = io.num_digital_outputs();

    let mut out = String::new();
    out.push_str("$date\n  (generated by RustPLC)\n$end\n");
    out.push_str("$version\n  rust_plc sim\n$end\n");
    out.push_str("$timescale 1ms $end\n");
    out.push_str("$scope module sim $end\n");

    // Deterministic ordering: DI first, then DO.
    for i in 0..num_di {
        let code = vcd_idcode(i);
        out.push_str("$var wire 1 ");
        out.push_str(&code);
        out.push(' ');
        out.push_str(&format!("di{i}"));
        out.push_str(" $end\n");
    }
    for i in 0..num_do {
        let code = vcd_idcode(num_di + i);
        out.push_str("$var wire 1 ");
        out.push_str(&code);
        out.push(' ');
        out.push_str(&format!("do{i}"));
        out.push_str(" $end\n");
    }

    out.push_str("$upscope $end\n");
    out.push_str("$enddefinitions $end\n");

    // Initial dump at time 0: assume all signals start low, and edges (including tick 0) will
    // drive any changes.
    out.push_str("#0\n$dumpvars\n");
    for i in 0..(num_di + num_do) {
        out.push('0');
        out.push_str(&vcd_idcode(i));
        out.push('\n');
    }
    out.push_str("$end\n");

    #[derive(Debug, Clone)]
    struct Change {
        time_ms: u64,
        index: usize,
        value: bool,
    }

    let mut changes: Vec<Change> = Vec::new();
    for e in io.digital_input_edges() {
        let idx = e.id.0 as usize;
        if idx < num_di {
            changes.push(Change {
                time_ms: e.tick.0.saturating_mul(tick_ms),
                index: idx,
                value: e.value,
            });
        }
    }
    for e in io.digital_output_edges() {
        let idx = e.id.0 as usize;
        if idx < num_do {
            changes.push(Change {
                time_ms: e.tick.0.saturating_mul(tick_ms),
                index: num_di + idx,
                value: e.value,
            });
        }
    }

    // Stable sorting: time first, then signal index (keeps output deterministic for same-time changes).
    changes.sort_by(|a, b| {
        a.time_ms
            .cmp(&b.time_ms)
            .then_with(|| a.index.cmp(&b.index))
    });

    let mut last_time: Option<u64> = Some(0);
    for c in changes {
        if last_time != Some(c.time_ms) {
            out.push('#');
            out.push_str(&c.time_ms.to_string());
            out.push('\n');
            last_time = Some(c.time_ms);
        }
        out.push(if c.value { '1' } else { '0' });
        out.push_str(&vcd_idcode(c.index));
        out.push('\n');
    }

    out
}

/// Export analog output edges to a minimal CSV (stepwise edges only).
///
/// Header columns: `time_ms,tick,ao_id,value`.
pub fn export_analog_outputs_csv(io: &SimIo, tick_ms: u64) -> String {
    let mut out = String::new();
    out.push_str("time_ms,tick,ao_id,value\n");
    for e in io.analog_output_edges() {
        let time_ms = e.tick.0.saturating_mul(tick_ms);
        out.push_str(&format!("{time_ms},{},{},{}\n", e.tick.0, e.id.0, e.value));
    }
    out
}

/// Export analog output edges to a minimal JSONL stream (one object per edge).
pub fn export_analog_outputs_jsonl(io: &SimIo, tick_ms: u64) -> String {
    #[derive(serde::Serialize)]
    struct Rec {
        time_ms: u64,
        tick: u64,
        ao_id: u16,
        value: f32,
    }

    let mut out = String::new();
    for e in io.analog_output_edges() {
        let rec = Rec {
            time_ms: e.tick.0.saturating_mul(tick_ms),
            tick: e.tick.0,
            ao_id: e.id.0,
            value: e.value,
        };
        let line = serde_json::to_string(&rec).expect("analog jsonl serializes");
        out.push_str(&line);
        out.push('\n');
    }
    out
}

fn vcd_idcode(mut n: usize) -> String {
    // VCD idcodes use a sequence of printable ASCII characters. This base-94 encoding is plenty
    // for our tiny simulations.
    const FIRST: u8 = 33; // '!'
    const LAST: u8 = 126; // '~'
    const BASE: usize = (LAST - FIRST + 1) as usize; // 94

    let mut buf: Vec<u8> = Vec::new();
    loop {
        let digit = (n % BASE) as u8;
        buf.push(FIRST + digit);
        n /= BASE;
        if n == 0 {
            break;
        }
    }
    buf.reverse();
    String::from_utf8(buf).expect("printable ascii")
}

#[cfg(test)]
mod tests {
    use super::*;
    use io_traits::{DigitalInputId, DigitalOutputId, Tick};
    use runtime_core::{Action, Instr, Program, Runtime, Step, StepId, Task};

    #[test]
    fn vcd_export_contains_signal_names_and_edges() {
        static STEP1_ACTIONS: [Action; 1] = [Action::SetDigital {
            id: DigitalOutputId(0),
            value: true,
        }];
        static STEPS: [Step<'static>; 3] = [
            Step {
                name: "wait_di0_true",
                instr: Instr::WaitDigital {
                    id: DigitalInputId(0),
                    equals: true,
                    next: StepId(1),
                    timeout: None,
                },
            },
            Step {
                name: "set_do0_true",
                instr: Instr::Action {
                    actions: &STEP1_ACTIONS,
                    next: StepId(2),
                },
            },
            Step {
                name: "halt",
                instr: Instr::Halt,
            },
        ];
        static TASKS: [Task<'static>; 1] = [Task {
            name: "main",
            steps: &STEPS,
            entry: StepId(0),
        }];
        static PROGRAM: Program<'static> = Program { tasks: &TASKS, pid_loops: &[] };

        let mut io = SimIo::new(1, 1, 0, 0);
        io.schedule_digital_input(Tick(1), DigitalInputId(0), true);

        let mut rt = Runtime::new(&PROGRAM).unwrap();
        for _ in 0..3 {
            rt.tick(&mut io).unwrap();
        }

        let vcd = export_vcd_digital(&io, 10);
        assert!(vcd.contains("di0"));
        assert!(vcd.contains("do0"));

        // Deterministic idcodes: di0 => "!", do0 => "\""
        assert!(vcd.contains("$var wire 1 ! di0 $end"));
        assert!(vcd.contains("$var wire 1 \" do0 $end"));
        assert!(vcd.contains("#10"));
        assert!(
            vcd.contains("1\""),
            "expected a rising edge on do0, got:\n{vcd}"
        );
    }
}
