[identity]
name = "OpenPLC Soft Controller"
type = "plc"

[[interfaces.ports]]
name = "X0"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X1"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X2"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X3"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X4"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X5"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X6"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X7"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X8"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X9"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X10"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X11"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X12"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X13"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X14"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X15"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X16"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X17"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X18"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X19"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X20"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X21"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X22"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X23"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X24"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X25"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X26"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X27"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X28"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X29"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X30"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "X31"
direction = "input"
port_type = "digital"

[[interfaces.ports]]
name = "Y0"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y1"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y2"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y3"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y4"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y5"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y6"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y7"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y8"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y9"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y10"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y11"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y12"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y13"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y14"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y15"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y16"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y17"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y18"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y19"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y20"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y21"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y22"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y23"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y24"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y25"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y26"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y27"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y28"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y29"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y30"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "Y31"
direction = "output"
port_type = "digital"

[[interfaces.ports]]
name = "AI0"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI1"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI2"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI3"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI4"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI5"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI6"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI7"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI8"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI9"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI10"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI11"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI12"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI13"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI14"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI15"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI16"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI17"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI18"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI19"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI20"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI21"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI22"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI23"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI24"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI25"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI26"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI27"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI28"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI29"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI30"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AI31"
direction = "input"
port_type = "analog"

[[interfaces.ports]]
name = "AO0"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO1"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO2"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO3"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO4"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO5"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO6"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO7"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO8"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO9"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO10"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO11"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO12"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO13"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO14"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO15"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO16"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO17"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO18"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO19"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO20"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO21"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO22"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO23"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO24"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO25"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO26"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO27"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO28"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO29"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO30"
direction = "output"
port_type = "analog"

[[interfaces.ports]]
name = "AO31"
direction = "output"
port_type = "analog"
