import React, { useEffect, useMemo, useState } from 'react';
import { Alert, Button, Card, Col, Empty, List, Row, Select, Space, Statistic, Table, Tag, Typography, Upload } from 'antd';
import { UploadOutlined, ReloadOutlined } from '@ant-design/icons';
import type { Edge, Node } from '@xyflow/react';
import TopologyCanvas from '../components/canvas/TopologyCanvas';
import { useTopologyStore, type NodeData } from '../stores/topologyStore';
import type {
  DevicePortMetadata,
  FlowchartArtifact,
  FlowchartTaskDiagram,
} from '../types';

const { Paragraph, Text, Title } = Typography;

const DEFAULT_ARTIFACT_URLS = [
  '/flowchart_review/flowchart.json',
  '/flowchart.json',
];

const MATERIAL_COLORS = [
  { fill: '#38bdf8', stroke: '#0369a1' },
  { fill: '#f97316', stroke: '#9a3412' },
  { fill: '#22c55e', stroke: '#166534' },
  { fill: '#eab308', stroke: '#854d0e' },
  { fill: '#a78bfa', stroke: '#5b21b6' },
  { fill: '#f43f5e', stroke: '#9f1239' },
];

interface ParsedEffect {
  kind: 'acquire' | 'transfer' | 'finish';
  from: string;
  to: string;
  label: string;
  taskName: string;
  effect: string;
}

interface FlowchartReviewPageProps {
  embedded?: boolean;
}

const FlowchartReviewPage: React.FC<FlowchartReviewPageProps> = ({ embedded = false }) => {
  const replaceTopology = useTopologyStore((state) => state.replaceTopology);
  const [artifact, setArtifact] = useState<FlowchartArtifact | null>(null);
  const [selectedTaskName, setSelectedTaskName] = useState<string | undefined>();
  const [loadState, setLoadState] = useState<'idle' | 'loading' | 'loaded' | 'missing' | 'error'>('idle');
  const [loadMessage, setLoadMessage] = useState<string>('');

  useEffect(() => {
    void loadDefaultArtifact();
  }, []);

  useEffect(() => {
    if (!artifact) {
      return;
    }
    const { nodes, edges } = flowchartTopologyToCanvas(artifact);
    replaceTopology(nodes, edges, false);
    setSelectedTaskName((current) => current ?? artifact.tasks[0]?.task_name);
  }, [artifact, replaceTopology]);

  const taskOptions = useMemo(
    () => artifact?.tasks.map((task) => ({ value: task.task_name, label: task.task_name })) ?? [],
    [artifact?.tasks]
  );

  const selectedTask = useMemo(
    () => artifact?.tasks.find((task) => task.task_name === selectedTaskName) ?? artifact?.tasks[0],
    [artifact?.tasks, selectedTaskName]
  );

  const effects = useMemo(() => collectEffects(artifact), [artifact]);
  const forwardEffects = useMemo(() => effects.filter(isForwardMaterialEffect), [effects]);
  const pipelineSites = useMemo(() => collectPipelineSites(forwardEffects), [forwardEffects]);
  const summary = useMemo(() => summarizeArtifact(artifact), [artifact]);

  async function loadDefaultArtifact() {
    setLoadState('loading');
    setLoadMessage('');
    for (const url of DEFAULT_ARTIFACT_URLS) {
      try {
        const response = await fetch(url, { cache: 'no-store' });
        if (!response.ok) {
          continue;
        }
        const nextArtifact = (await response.json()) as FlowchartArtifact;
        setArtifact(nextArtifact);
        setLoadState('loaded');
        setLoadMessage(`loaded ${url}`);
        return;
      } catch {
        // Try the next conventional location.
      }
    }
    setLoadState('missing');
    setLoadMessage('No bundled flowchart.json was found. Upload the artifact generated by rust_plc flowchart.');
  }

  async function handleUpload(file: File) {
    try {
      const text = await file.text();
      const nextArtifact = JSON.parse(text) as FlowchartArtifact;
      setArtifact(nextArtifact);
      setLoadState('loaded');
      setLoadMessage(file.name);
    } catch (error) {
      setLoadState('error');
      setLoadMessage(error instanceof Error ? error.message : 'Invalid flowchart JSON');
    }
    return false;
  }

  return (
    <div style={{ padding: embedded ? 0 : 24, display: 'grid', gap: 18 }}>
      <Card
        style={{
          borderColor: '#164e63',
          background:
            'radial-gradient(circle at 10% 0%, rgba(56,189,248,0.18), transparent 32%), linear-gradient(135deg, #0f172a 0%, #111827 56%, #171717 100%)',
        }}
      >
        <Row gutter={[18, 18]} align="middle">
          <Col xs={24} xl={15}>
            <Space direction="vertical" size={8} style={{ width: '100%' }}>
              <Tag color="cyan">TS / Tailwind review surface</Tag>
              <Title level={2} style={{ margin: 0 }}>
                Flowchart Review Cockpit
              </Title>
              <Paragraph style={{ color: '#cbd5e1', marginBottom: 0, maxWidth: 900 }}>
                旧的 Web UI 是承载层。这里读取 CLI 生成的 flowchart artifact，把拓扑放回 React Flow 主画布，
                再把 system contract、并行物料波形、任务 SFC 和 effect reel 作为同一个审阅界面。
              </Paragraph>
              <Text type="secondary">{loadMessage}</Text>
            </Space>
          </Col>
          <Col xs={24} xl={9}>
            <Space wrap style={{ justifyContent: 'flex-end', width: '100%' }}>
              <Button icon={<ReloadOutlined />} onClick={loadDefaultArtifact} loading={loadState === 'loading'}>
                Reload bundled JSON
              </Button>
              <Upload beforeUpload={handleUpload} showUploadList={false} accept="application/json,.json">
                <Button type="primary" icon={<UploadOutlined />}>
                  Upload flowchart.json
                </Button>
              </Upload>
            </Space>
          </Col>
        </Row>
      </Card>

      {!artifact ? (
        <Card>
          {loadState === 'error' && <Alert type="error" message="Flowchart JSON load failed" description={loadMessage} showIcon />}
          {loadState !== 'error' && (
            <Empty
              description="No flowchart artifact is loaded yet."
              image={Empty.PRESENTED_IMAGE_SIMPLE}
            />
          )}
        </Card>
      ) : (
        <>
          <Row gutter={[18, 18]}>
            <Col xs={24} xl={6}>
              <MetricCard title="Tasks" value={summary.taskCount} />
            </Col>
            <Col xs={24} xl={6}>
              <MetricCard title="Steps" value={summary.stepCount} />
            </Col>
            <Col xs={24} xl={6}>
              <MetricCard title="Transitions" value={summary.transitionCount} />
            </Col>
            <Col xs={24} xl={6}>
              <MetricCard title="Topology Links" value={artifact.topology.link_count} />
            </Col>
          </Row>

          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'minmax(520px, 1.12fr) minmax(460px, 0.88fr)',
              gap: 18,
              minHeight: 620,
            }}
          >
            <Card
              title="Recovered Topology Canvas"
              extra={<Tag color="blue">{artifact.topology.device_count} devices</Tag>}
              styles={{ body: { height: 640, padding: 0 } }}
            >
              <TopologyCanvas readOnly showReadOnlyNotice={false} />
            </Card>

            <Space direction="vertical" size={18} style={{ width: '100%' }}>
              <Card title="System Contract">
                {artifact.system_contract ? (
                  <Space direction="vertical" size={8} style={{ width: '100%' }}>
                    <Text code>{artifact.system_contract.path}</Text>
                    <Text type="secondary">{artifact.system_contract.byte_count} bytes</Text>
                    <pre style={contractPreStyle}>{artifact.system_contract.excerpt}</pre>
                  </Space>
                ) : (
                  <Alert
                    type="warning"
                    showIcon
                    message="No system contract was found beside the PLC bundle."
                  />
                )}
              </Card>

              <Card title="Task Inventory">
                <Select
                  value={selectedTask?.task_name}
                  options={taskOptions}
                  onChange={setSelectedTaskName}
                  style={{ width: '100%', marginBottom: 12 }}
                  showSearch
                />
                {selectedTask && <TaskSummary task={selectedTask} />}
              </Card>
            </Space>
          </div>

          <Card title="Parallel Material Occupancy Map">
            <PipelineMap sites={pipelineSites} effects={forwardEffects} />
          </Card>

          <Row gutter={[18, 18]}>
            <Col xs={24} xl={12}>
              <Card title="Effect Reel">
                <List
                  size="small"
                  dataSource={effects.slice(0, 24)}
                  renderItem={(item, index) => (
                    <List.Item>
                      <Space direction="vertical" size={2}>
                        <Text>
                          <Tag color={effectTagColor(item.kind)}>{index + 1}</Tag>
                          {item.label}
                        </Text>
                        <Text type="secondary">{item.taskName} / {item.effect}</Text>
                      </Space>
                    </List.Item>
                  )}
                />
              </Card>
            </Col>
            <Col xs={24} xl={12}>
              <Card title="Topology Ledger">
                <Table
                  size="small"
                  pagination={{ pageSize: 8, size: 'small' }}
                  dataSource={artifact.topology.links.map((link, index) => ({ key: index, link }))}
                  columns={[{ title: 'Link', dataIndex: 'link' }]}
                />
              </Card>
            </Col>
          </Row>
        </>
      )}
    </div>
  );
};

const MetricCard: React.FC<{ title: string; value: number }> = ({ title, value }) => (
  <Card>
    <Statistic title={title} value={value} />
  </Card>
);

const TaskSummary: React.FC<{ task: FlowchartTaskDiagram }> = ({ task }) => (
  <Space direction="vertical" size={12} style={{ width: '100%' }}>
    <Space wrap>
      <Tag color="geekblue">{task.steps.length} steps</Tag>
      <Tag color="purple">{task.transitions.length} transitions</Tag>
      <Tag color={taskRoleColor(task.task_name)}>{taskRole(task.task_name)}</Tag>
    </Space>
    <div style={sfcStripStyle}>
      {task.steps.map((step, index) => (
        <React.Fragment key={step.step_name}>
          <div style={sfcStepStyle} title={step.statements.join('\n')}>
            <Text strong>{step.step_name}</Text>
            <Text type="secondary" style={{ fontSize: 11 }}>
              {shortSource(step.source)}:{step.line}
            </Text>
          </div>
          {index < task.steps.length - 1 && <div style={sfcTransitionStyle}>T</div>}
        </React.Fragment>
      ))}
    </div>
    <List
      size="small"
      dataSource={task.transitions.slice(0, 10)}
      renderItem={(transition) => (
        <List.Item>
          <Space direction="vertical" size={2}>
            <Text>{`${transition.from_step} -> ${transition.to_step}`}</Text>
            <Text type="secondary">{transition.guard}</Text>
          </Space>
        </List.Item>
      )}
    />
  </Space>
);

const PipelineMap: React.FC<{ sites: string[]; effects: ParsedEffect[] }> = ({ sites, effects }) => {
  if (sites.length === 0) {
    return <Empty description="No forward workpiece effects were available for pipeline projection." />;
  }

  const width = Math.max(980, sites.length * 170);
  const left = 80;
  const right = width - 80;
  const y = 105;
  const xFor = (index: number) => left + (sites.length <= 1 ? 0 : (index * (right - left)) / (sites.length - 1));
  const indexBySite = new Map(sites.map((site, index) => [site, index]));

  return (
    <div style={{ overflowX: 'auto', borderRadius: 14, background: '#020617', border: '1px solid #1e293b' }}>
      <svg width={width} height={260} role="img" aria-label="parallel material occupancy map">
        <defs>
          <marker id="flowArrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto">
            <path d="M0,0 L8,4 L0,8 z" fill="#64748b" />
          </marker>
        </defs>
        <text x={left} y={36} fill="#93c5fd" fontFamily="Cascadia Code, Consolas, monospace" fontSize="13">
          steady-state multi-wafer projection
        </text>
        <text x={left} y={56} fill="#94a3b8" fontFamily="Cascadia Code, Consolas, monospace" fontSize="11">
          colors indicate different wafers occupying nearby stations, not one serial wafer path
        </text>
        <line x1={left} y1={y} x2={right} y2={y} stroke="#334155" strokeWidth="5" strokeLinecap="round" />
        {effects.map((effect, index) => {
          const from = indexBySite.get(effect.from);
          const to = indexBySite.get(effect.to);
          if (from === undefined || to === undefined) {
            return null;
          }
          return (
            <line
              key={`${effect.taskName}-${effect.effect}-${index}`}
              x1={xFor(from)}
              y1={y}
              x2={xFor(to)}
              y2={y}
              stroke="#64748b"
              strokeWidth="2"
              markerEnd="url(#flowArrow)"
              opacity={0.72}
            />
          );
        })}
        {sites.map((site, index) => {
          const color = MATERIAL_COLORS[index % MATERIAL_COLORS.length];
          const x = xFor(index);
          return (
            <g key={site}>
              <circle cx={x} cy={y} r="17" fill={color.fill} stroke={color.stroke} strokeWidth="2" />
              <text x={x} y={y + 4} textAnchor="middle" fill="#0f172a" fontWeight="700" fontSize="11">
                W{index + 1}
              </text>
              <text x={x} y={y + 48} textAnchor="middle" fill="#e2e8f0" fontSize="11" fontFamily="Cascadia Code, Consolas, monospace">
                {compactSite(site)}
              </text>
              <title>{site}</title>
            </g>
          );
        })}
      </svg>
    </div>
  );
};

export function flowchartTopologyToCanvas(artifact: FlowchartArtifact): { nodes: Node<NodeData>[]; edges: Edge[] } {
  const linkRows = artifact.topology.links.map(parseTopologyLink).filter((item): item is ParsedLink => Boolean(item));
  const nodeNames = new Set<string>();

  (artifact.topology.devices ?? []).forEach((device) => nodeNames.add(device.split(':')[0]));
  linkRows.forEach((link) => {
    nodeNames.add(link.from);
    nodeNames.add(link.to);
  });

  const layout = buildIndustrialTopologyLayout(Array.from(nodeNames), linkRows, [], artifact);
  const nodes: Node<NodeData>[] = layout.names.map((name) => {
    const stage = layout.stageByName.get(name) ?? stageName(name);
    const lane = layout.laneByName.get(name) ?? laneForName(name, artifact);
    const nodeType = nodeTypeForName(name);
    return {
      id: name,
      type: nodeType,
      position: layout.positions.get(name) ?? { x: 0, y: 0 },
      data: {
        label: name,
        type: nodeType,
        status: isWorkpieceEndpoint(name, artifact) ? 'active' : 'idle',
        device_type: stage,
        layout_lane: lane,
        ports: portsForNode(nodeType),
        tags: {
          functional_group: [stage.toLowerCase()],
          danger_level: lane === 'material' ? ['workpiece'] : [],
          location_group: [`flowchart/${stage.toLowerCase()}`, `flowchart/${stage.toLowerCase()}/${lane}`],
        },
      },
    };
  });

  const edges: Edge[] = [
    ...linkRows.map((link, index) => ({
      id: `flowchart-link-${index}`,
      source: link.from,
      target: link.to,
      sourceHandle: sourceHandleForNode(link.from),
      targetHandle: targetHandleForNode(link.to),
      label: undefined,
      data: { relation: link.relation, hideLabel: true },
      style: {
        stroke: relationColor(link.relation),
        strokeWidth: 1.8,
      },
    })),
  ];

  return { nodes, edges };
}

type TopologyLane = 'material' | 'actuator' | 'command' | 'feedback' | 'io' | 'system';

interface TopologyLayout {
  names: string[];
  positions: Map<string, { x: number; y: number }>;
  stageByName: Map<string, string>;
  laneByName: Map<string, TopologyLane>;
}

const STAGE_ORDER = ['FEED', 'SLIDE', 'ARM', 'ORIENT', 'TRANSFER', 'MEASURE', 'REJECT', 'IO', 'SYSTEM'];
const LANE_Y: Record<TopologyLane, number> = {
  material: 70,
  actuator: 205,
  command: 395,
  feedback: 585,
  io: 860,
  system: 1100,
};

const COMMAND_ACTUATOR_PATTERN = /(^|_)vac_.*_valve$|^vac_.*valve$|_vac_valve$/i;
const CONTROL_CHAIN_X = {
  output: -430,
  command: -225,
  actuator: 0,
  feedback: 250,
  input: 470,
} as const;
const CONTROL_CHAIN_START_Y = 210;
const CONTROL_CHAIN_ITEM_GAP = 118;
const CONTROL_CHAIN_BLOCK_GAP = 76;
const CONTROL_CHAIN_MIN_BLOCK_HEIGHT = 136;
const GENERIC_GRID_X_GAP = 170;
const GENERIC_GRID_Y_GAP = 132;

function buildIndustrialTopologyLayout(
  names: string[],
  links: ParsedLink[],
  materialEffects: ParsedEffect[],
  artifact: FlowchartArtifact
): TopologyLayout {
  const adjacency = buildAdjacency(links, materialEffects);
  const stageByName = inferConnectedStages(names, links, materialEffects);
  const laneByName = new Map(names.map((name) => [name, laneForName(name, artifact)]));

  const grouped = new Map<string, Map<TopologyLane, string[]>>();
  names.forEach((name) => {
    const stage = stageByName.get(name) ?? stageName(name);
    const lane = laneByName.get(name) ?? 'system';
    if (!grouped.has(stage)) {
      grouped.set(stage, new Map());
    }
    const stageGroup = grouped.get(stage)!;
    stageGroup.set(lane, [...(stageGroup.get(lane) ?? []), name]);
  });

  const activeStages = STAGE_ORDER.filter((stage) => grouped.has(stage));
  const positions = new Map<string, { x: number; y: number }>();
  const orderedNames: string[] = [];
  const stageX = new Map<string, number>();
  const stageWidth = new Map<string, number>();

  activeStages.forEach((stage) => {
    const stageGroup = grouped.get(stage)!;
    const maxLaneCount = Math.max(...Array.from(stageGroup.values()).map((items) => items.length), 1);
    const laneColumnCount = Math.min(7, Math.max(1, Math.ceil(Math.sqrt(maxLaneCount * 1.7))));
    const couplingRootCount = couplingRootsForStage(stageGroup).length;
    const hasFeedbackTerminalPairs =
      (stageGroup.get('feedback')?.length ?? 0) > 0 && (stageGroup.get('io')?.length ?? 0) > 0;
    stageWidth.set(stage, Math.max(couplingRootCount > 0 || hasFeedbackTerminalPairs ? 1120 : 560, 260 + laneColumnCount * GENERIC_GRID_X_GAP));
  });

  activeStages.reduce((cursor, stage) => {
    stageX.set(stage, cursor + (stageWidth.get(stage) ?? 340) / 2);
    return cursor + (stageWidth.get(stage) ?? 340) + 160;
  }, 120);

  activeStages.forEach((stage) => {
    const stageGroup = grouped.get(stage)!;
    const xCenter = stageX.get(stage) ?? 120;
    const availableWidth = Math.max(220, (stageWidth.get(stage) ?? 340) - 120);
    const horizontalStep = GENERIC_GRID_X_GAP;
    const verticalStep = GENERIC_GRID_Y_GAP;

    (Object.keys(LANE_Y) as TopologyLane[]).forEach((lane) => {
      const laneItems = (stageGroup.get(lane) ?? []).sort((left, right) =>
        layoutOrderKey(left, adjacency, stageX, stageByName).localeCompare(layoutOrderKey(right, adjacency, stageX, stageByName))
      );
      const columnCount = Math.max(
        1,
        Math.min(
          laneItems.length,
          Math.max(1, Math.floor(availableWidth / horizontalStep))
        )
      );
      const gridWidth = (columnCount - 1) * horizontalStep;
      laneItems.forEach((name, index) => {
        const col = index % columnCount;
        const row = Math.floor(index / columnCount);
        positions.set(name, {
          x: xCenter - gridWidth / 2 + col * horizontalStep,
          y: LANE_Y[lane] + row * verticalStep,
        });
        orderedNames.push(name);
      });
    });
  });

  applyActuatorCouplingLayout({
    activeStages,
    grouped,
    links,
    positions,
    stageX,
    stageWidth,
    laneByName,
  });

  return { names: orderedNames, positions, stageByName, laneByName };
}

interface CouplingLayoutContext {
  activeStages: string[];
  grouped: Map<string, Map<TopologyLane, string[]>>;
  links: ParsedLink[];
  positions: Map<string, { x: number; y: number }>;
  stageX: Map<string, number>;
  stageWidth: Map<string, number>;
  laneByName: Map<string, TopologyLane>;
}

function applyActuatorCouplingLayout(ctx: CouplingLayoutContext) {
  const incoming = new Map<string, ParsedLink[]>();
  const outgoing = new Map<string, ParsedLink[]>();
  ctx.links.forEach((link) => {
    incoming.set(link.to, [...(incoming.get(link.to) ?? []), link]);
    outgoing.set(link.from, [...(outgoing.get(link.from) ?? []), link]);
  });

  ctx.activeStages.forEach((stage) => {
    const stageGroup = ctx.grouped.get(stage);
    const actuators = couplingRootsForStage(stageGroup)
      .filter((name) => hasCouplingEdges(name, incoming, outgoing, ctx.laneByName))
      .sort();

    if (!stageGroup) {
      return;
    }

    const xCenter = ctx.stageX.get(stage) ?? 120;
    const assigned = new Set<string>();
    const x = {
      output: xCenter + CONTROL_CHAIN_X.output,
      command: xCenter + CONTROL_CHAIN_X.command,
      actuator: xCenter + CONTROL_CHAIN_X.actuator,
      feedback: xCenter + CONTROL_CHAIN_X.feedback,
      input: xCenter + CONTROL_CHAIN_X.input,
    };
    let yCursor = CONTROL_CHAIN_START_Y;

    actuators.forEach((actuator) => {
      const commands = uniqueSorted([
        ...directPredecessors(actuator, incoming).filter((name) => ctx.laneByName.get(name) === 'command'),
      ]);
      const directOutputs = directPredecessors(actuator, incoming).filter((name) => ctx.laneByName.get(name) === 'io');
      const commandOutputs = commands.flatMap((command) =>
        directPredecessors(command, incoming).filter((name) => ctx.laneByName.get(name) === 'io')
      );
      const outputs = uniqueSorted([...directOutputs, ...commandOutputs]);
      const feedbacks = uniqueSorted(
        directSuccessors(actuator, outgoing).filter((name) => ctx.laneByName.get(name) === 'feedback')
      );
      const feedbackInputs = feedbacks.flatMap((feedback) =>
        directSuccessors(feedback, outgoing).filter((name) => ctx.laneByName.get(name) === 'io')
      );
      const inputs = uniqueSorted(feedbackInputs);
      const commandColumn = isCommandActuator(actuator) ? uniqueSorted([...commands, actuator]) : commands;
      const actuatorColumn = isCommandActuator(actuator) ? [] : [actuator];
      const maxColumnItems = Math.max(
        outputs.length,
        commandColumn.length,
        actuatorColumn.length,
        feedbacks.length,
        inputs.length,
        1
      );
      const blockHeight = Math.max(
        CONTROL_CHAIN_MIN_BLOCK_HEIGHT,
        56 + (maxColumnItems - 1) * CONTROL_CHAIN_ITEM_GAP
      );
      const yBase = yCursor + blockHeight / 2;

      setStackedPositions(ctx.positions, outputs, x.output, yBase, CONTROL_CHAIN_ITEM_GAP);
      setStackedPositions(ctx.positions, commandColumn, x.command, yBase, CONTROL_CHAIN_ITEM_GAP);
      setStackedPositions(ctx.positions, actuatorColumn, x.actuator, yBase, CONTROL_CHAIN_ITEM_GAP);
      setStackedPositions(ctx.positions, feedbacks, x.feedback, yBase, CONTROL_CHAIN_ITEM_GAP);
      setStackedPositions(ctx.positions, inputs, x.input, yBase, CONTROL_CHAIN_ITEM_GAP);
      [
        ...outputs,
        ...commandColumn,
        ...actuatorColumn,
        ...feedbacks,
        ...inputs,
      ].forEach((name) => assigned.add(name));
      yCursor += blockHeight + CONTROL_CHAIN_BLOCK_GAP;
    });

    const feedbackPairs = uniqueSorted(stageGroup.get('feedback') ?? [])
      .filter((feedback) => !assigned.has(feedback))
      .map((feedback) => ({
        feedback,
        inputs: uniqueSorted(
          directSuccessors(feedback, outgoing).filter((name) => ctx.laneByName.get(name) === 'io' && !assigned.has(name))
        ),
      }))
      .filter((pair) => pair.inputs.length > 0);

    feedbackPairs.forEach(({ feedback, inputs }) => {
      const maxColumnItems = Math.max(1, inputs.length);
      const blockHeight = Math.max(
        CONTROL_CHAIN_MIN_BLOCK_HEIGHT,
        56 + (maxColumnItems - 1) * CONTROL_CHAIN_ITEM_GAP
      );
      const yBase = yCursor + blockHeight / 2;
      ctx.positions.set(feedback, { x: x.feedback, y: yBase });
      setStackedPositions(ctx.positions, inputs, x.input, yBase, CONTROL_CHAIN_ITEM_GAP);
      assigned.add(feedback);
      inputs.forEach((name) => assigned.add(name));
      yCursor += blockHeight + CONTROL_CHAIN_BLOCK_GAP;
    });

    placeRemainingStageNodes({
      stageGroup,
      positions: ctx.positions,
      laneByName: ctx.laneByName,
      assigned,
      xCenter,
      yStart: Math.max(yCursor, CONTROL_CHAIN_START_Y + CONTROL_CHAIN_MIN_BLOCK_HEIGHT),
    });
  });
}

function placeRemainingStageNodes({
  stageGroup,
  positions,
  laneByName,
  assigned,
  xCenter,
  yStart,
}: {
  stageGroup: Map<TopologyLane, string[]>;
  positions: Map<string, { x: number; y: number }>;
  laneByName: Map<string, TopologyLane>;
  assigned: Set<string>;
  xCenter: number;
  yStart: number;
}) {
  const remaining = Array.from(new Set(Array.from(stageGroup.values()).flat()))
    .filter((name) => !assigned.has(name))
    .sort();
  const byLane = new Map<TopologyLane, string[]>();
  remaining.forEach((name) => {
    const lane = laneByName.get(name) ?? 'system';
    byLane.set(lane, [...(byLane.get(lane) ?? []), name]);
  });

  let yCursor = yStart;
  (['material', 'command', 'actuator', 'feedback', 'io', 'system'] as TopologyLane[]).forEach((lane) => {
    const items = byLane.get(lane) ?? [];
    if (items.length === 0) {
      return;
    }
    const xBase = xCenter + fallbackLaneOffset(lane, items);
    const columnCount = Math.min(3, Math.max(1, Math.ceil(Math.sqrt(items.length))));
    const gridWidth = (columnCount - 1) * GENERIC_GRID_X_GAP;
    items.forEach((name, index) => {
      const col = index % columnCount;
      const row = Math.floor(index / columnCount);
      positions.set(name, {
        x: xBase - gridWidth / 2 + col * GENERIC_GRID_X_GAP,
        y: yCursor + row * GENERIC_GRID_Y_GAP,
      });
    });
    yCursor += Math.ceil(items.length / columnCount) * GENERIC_GRID_Y_GAP + 48;
  });
}

function fallbackLaneOffset(lane: TopologyLane, names: string[]): number {
  if (lane === 'material') return 0;
  if (lane === 'command') return CONTROL_CHAIN_X.command;
  if (lane === 'actuator') return CONTROL_CHAIN_X.actuator;
  if (lane === 'feedback') return CONTROL_CHAIN_X.feedback;
  if (lane === 'io') {
    return names.some((name) => /^x\d+$/i.test(name)) && !names.some((name) => /^y\d+$/i.test(name))
      ? CONTROL_CHAIN_X.input
      : CONTROL_CHAIN_X.output;
  }
  return 0;
}

function couplingRootsForStage(stageGroup: Map<TopologyLane, string[]> | undefined): string[] {
  if (!stageGroup) {
    return [];
  }
  return [
    ...(stageGroup.get('actuator') ?? []),
    ...(stageGroup.get('command') ?? []).filter(isCommandActuator),
  ];
}

function isCommandActuator(name: string): boolean {
  return COMMAND_ACTUATOR_PATTERN.test(name.toLowerCase());
}

function hasCouplingEdges(
  name: string,
  incoming: Map<string, ParsedLink[]>,
  outgoing: Map<string, ParsedLink[]>,
  laneByName: Map<string, TopologyLane>
): boolean {
  return [
    ...directPredecessors(name, incoming),
    ...directSuccessors(name, outgoing),
  ].some((neighbor) => {
    const lane = laneByName.get(neighbor);
    return lane === 'command' || lane === 'feedback' || lane === 'io';
  });
}

function directPredecessors(name: string, incoming: Map<string, ParsedLink[]>): string[] {
  return (incoming.get(name) ?? []).map((link) => link.from);
}

function directSuccessors(name: string, outgoing: Map<string, ParsedLink[]>): string[] {
  return (outgoing.get(name) ?? []).map((link) => link.to);
}

function uniqueSorted(values: string[]): string[] {
  return Array.from(new Set(values)).sort();
}

function setStackedPositions(
  positions: Map<string, { x: number; y: number }>,
  names: string[],
  x: number,
  yCenter: number,
  step: number
) {
  if (names.length === 0) {
    return;
  }
  const firstY = yCenter - ((names.length - 1) * step) / 2;
  names.forEach((name, index) => {
    positions.set(name, { x, y: firstY + index * step });
  });
}

function buildAdjacency(links: ParsedLink[], materialEffects: ParsedEffect[]): Map<string, Set<string>> {
  const adjacency = new Map<string, Set<string>>();
  const connect = (left: string, right: string) => {
    if (!adjacency.has(left)) adjacency.set(left, new Set());
    if (!adjacency.has(right)) adjacency.set(right, new Set());
    adjacency.get(left)!.add(right);
    adjacency.get(right)!.add(left);
  };
  links.forEach((link) => connect(link.from, link.to));
  materialEffects.forEach((effect) => connect(effect.from, effect.to));
  return adjacency;
}

function inferConnectedStages(
  names: string[],
  links: ParsedLink[],
  materialEffects: ParsedEffect[]
): Map<string, string> {
  const inferred = new Map(names.map((name) => [name, stageName(name)]));
  const relationEdges = links.map((link) => [link.from, link.to] as const);
  const materialEdges = materialEffects.map((effect) => [effect.from, effect.to] as const);

  for (let pass = 0; pass < 3; pass += 1) {
    [...relationEdges, ...materialEdges].forEach(([from, to]) => {
      const fromStage = inferred.get(from) ?? stageName(from);
      const toStage = inferred.get(to) ?? stageName(to);
      if (fromStage === 'IO' && toStage !== 'IO' && toStage !== 'SYSTEM') {
        inferred.set(from, toStage);
      }
      if (toStage === 'IO' && fromStage !== 'IO' && fromStage !== 'SYSTEM') {
        inferred.set(to, fromStage);
      }
      if (fromStage === 'SYSTEM' && toStage !== 'SYSTEM') {
        inferred.set(from, toStage);
      }
      if (toStage === 'SYSTEM' && fromStage !== 'SYSTEM') {
        inferred.set(to, fromStage);
      }
    });
  }

  return inferred;
}

function laneForName(name: string, artifact: FlowchartArtifact): TopologyLane {
  const lower = name.toLowerCase();
  if (isWorkpieceEndpoint(name, artifact) || lower.includes('nozzle') || lower.includes('ejector')) return 'material';
  if (/^[xy]\d+$/i.test(name) || lower.includes('plc_main')) return 'io';
  if (lower.includes('sensor') || lower.includes('wafer_on') || lower.includes('ready') || lower.includes('detect')) return 'feedback';
  if (lower.includes('button') || lower.includes('mode_')) return 'feedback';
  if (lower.includes('valve') || lower.startsWith('y')) return 'command';
  if (lower.includes('cyl') || lower.includes('axis') || lower.includes('motor') || lower.includes('swing') || lower.includes('lift')) return 'actuator';
  return 'system';
}

function layoutOrderKey(
  name: string,
  adjacency: Map<string, Set<string>>,
  stageX: Map<string, number>,
  stageByName: Map<string, string>
): string {
  const neighbors = Array.from(adjacency.get(name) ?? []);
  if (neighbors.length === 0) {
    return `9999-${name}`;
  }
  const barycenter =
    neighbors.reduce((sum, neighbor) => sum + (stageX.get(stageByName.get(neighbor) ?? stageName(neighbor)) ?? 0), 0) /
    neighbors.length;
  return `${String(Math.round(barycenter)).padStart(5, '0')}-${name}`;
}

interface ParsedLink {
  from: string;
  to: string;
  relation: string;
}

function parseTopologyLink(raw: string): ParsedLink | null {
  const match = /^(.+?)\s*->\s*(.+?)\s*\((.+)\)$/.exec(raw.trim());
  if (!match) {
    return null;
  }
  return {
    from: match[1].trim(),
    to: match[2].trim(),
    relation: match[3].trim(),
  };
}

function collectEffects(artifact: FlowchartArtifact | null): ParsedEffect[] {
  if (!artifact) {
    return [];
  }
  return artifact.tasks.flatMap((task) =>
    task.transitions.flatMap((transition) =>
      transition.effects
        .map((effect) => parseEffect(effect, task.task_name))
        .filter((item): item is ParsedEffect => Boolean(item))
    )
  );
}

function parseEffect(effect: string, taskName: string): ParsedEffect | null {
  let match = /^acquire (.+) from (.+)$/.exec(effect);
  if (match) {
    return { kind: 'acquire', from: match[2], to: match[1], label: `${match[2]} -> ${match[1]}`, taskName, effect };
  }
  match = /^transfer (.+) -> (.+)$/.exec(effect);
  if (match) {
    return { kind: 'transfer', from: match[1], to: match[2], label: `${match[1]} -> ${match[2]}`, taskName, effect };
  }
  match = /^finish (.+) as (.+)$/.exec(effect);
  if (match) {
    return { kind: 'finish', from: match[1], to: match[2], label: `${match[1]} -> ${match[2]}`, taskName, effect };
  }
  return null;
}

function isForwardMaterialEffect(effect: ParsedEffect): boolean {
  if (effect.kind === 'finish') {
    return false;
  }
  const text = `${effect.from} ${effect.to}`.toLowerCase();
  if (text.includes('reject') || text.includes('drop') || text.includes('scrap')) {
    return false;
  }
  return stageIndex(stageName(effect.to)) >= stageIndex(stageName(effect.from));
}

function collectPipelineSites(effects: ParsedEffect[]): string[] {
  const seen = new Set<string>();
  const sites: string[] = [];
  effects.forEach((effect) => {
    [effect.from, effect.to].forEach((site) => {
      if (seen.has(site)) {
        return;
      }
      seen.add(site);
      sites.push(site);
    });
  });
  return sites.sort((left, right) => stageSortKey(left).localeCompare(stageSortKey(right)));
}

function summarizeArtifact(artifact: FlowchartArtifact | null) {
  const tasks = artifact?.tasks ?? [];
  return {
    taskCount: tasks.length,
    stepCount: tasks.reduce((sum, task) => sum + task.steps.length, 0),
    transitionCount: tasks.reduce((sum, task) => sum + task.transitions.length, 0),
  };
}

function taskRole(name: string): string {
  const lower = name.toLowerCase();
  if (lower.includes('fault') || lower.includes('warning')) return 'fault';
  if (lower.includes('manual') || lower.includes('maintenance') || lower.includes('check')) return 'service';
  if (lower.includes('startup') || lower.includes('init')) return 'startup';
  if (lower.includes('monitor') || lower.includes('supervisor')) return 'monitor';
  return 'process';
}

function taskRoleColor(name: string): string {
  const role = taskRole(name);
  if (role === 'fault') return 'red';
  if (role === 'service') return 'gold';
  if (role === 'startup') return 'cyan';
  if (role === 'monitor') return 'blue';
  return 'green';
}

function effectTagColor(kind: ParsedEffect['kind']): string {
  if (kind === 'acquire') return 'cyan';
  if (kind === 'finish') return 'gold';
  return 'green';
}

function nodeTypeForName(name: string): string {
  const lower = name.toLowerCase();
  if (/^x\d+$/i.test(name)) return 'input_terminal';
  if (/^y\d+$/i.test(name)) return 'output_terminal';
  if (lower.includes('sensor') || lower.includes('wafer_on') || lower.includes('ready')) return 'sensor';
  if (lower.includes('button') || lower.includes('mode_')) return 'switch';
  if (lower.includes('cyl')) return 'cylinder';
  if (lower.includes('axis') || lower.includes('motor')) return 'stepper_pd';
  return 'generic';
}

function portsForNode(nodeType: string): DevicePortMetadata[] {
  if (nodeType === 'input_terminal') return [{ id: 'in', type: 'digital', role: 'consumer' }];
  if (nodeType === 'output_terminal') return [{ id: 'out', type: 'digital', role: 'producer' }];
  return [
    { id: 'in', type: 'generic', role: 'consumer' },
    { id: 'out', type: 'generic', role: 'producer' },
  ];
}

function sourceHandleForNode(name: string): string {
  return /^x\d+$/i.test(name) ? 'in' : 'out';
}

function targetHandleForNode(name: string): string {
  return /^y\d+$/i.test(name) ? 'out' : 'in';
}

function relationColor(relation: string): string {
  const lower = relation.toLowerCase();
  if (lower.includes('electrical')) return '#38bdf8';
  if (lower.includes('pneumatic')) return '#f97316';
  if (lower.includes('logical')) return '#22c55e';
  return '#94a3b8';
}

function stageName(name: string): string {
  const lower = name.toLowerCase();
  if (lower.includes('feed') || lower.includes('cassette')) return 'FEED';
  if (lower.includes('slide')) return 'SLIDE';
  if (lower.includes('arm')) return 'ARM';
  if (lower.includes('orient')) return 'ORIENT';
  if (lower.includes('transfer') || lower.includes('swing') || lower.includes('lift')) return 'TRANSFER';
  if (lower.includes('measure')) return 'MEASURE';
  if (/^[xy]\d+$/i.test(name) || lower.includes('plc') || lower.includes('mode') || lower.includes('button')) return 'IO';
  return 'SYSTEM';
}

function stageIndex(stage: string): number {
  return ['FEED', 'SLIDE', 'ARM', 'ORIENT', 'TRANSFER', 'MEASURE', 'IO', 'SYSTEM'].indexOf(stage);
}

function stageSortKey(name: string): string {
  const stage = stageName(name);
  return `${String(stageIndex(stage)).padStart(2, '0')}-${name}`;
}

function compactSite(name: string): string {
  return name.length > 18 ? `${name.slice(0, 15)}...` : name;
}

function shortSource(source: string): string {
  const normalized = source.replaceAll('\\', '/');
  const segments = normalized.split('/');
  return segments.slice(-2).join('/');
}

function isWorkpieceEndpoint(name: string, artifact: FlowchartArtifact): boolean {
  return artifact.topology.workpiece_sites.some((site) => site.startsWith(`${name}:`)) ||
    artifact.topology.workpiece_holders.some((holder) => holder.startsWith(`${name}:`));
}

const contractPreStyle: React.CSSProperties = {
  maxHeight: 220,
  overflow: 'auto',
  whiteSpace: 'pre-wrap',
  background: '#020617',
  border: '1px solid #1e293b',
  borderRadius: 12,
  padding: 14,
  color: '#e2e8f0',
  lineHeight: 1.55,
};

const sfcStripStyle: React.CSSProperties = {
  display: 'flex',
  gap: 8,
  overflowX: 'auto',
  padding: '10px 2px',
};

const sfcStepStyle: React.CSSProperties = {
  minWidth: 150,
  maxWidth: 180,
  display: 'grid',
  gap: 4,
  border: '1px solid #334155',
  background: '#111827',
  borderRadius: 6,
  padding: '9px 10px',
};

const sfcTransitionStyle: React.CSSProperties = {
  alignSelf: 'center',
  minWidth: 28,
  height: 2,
  background: '#64748b',
  color: '#94a3b8',
  fontSize: 10,
  textAlign: 'center',
};

export default FlowchartReviewPage;
