import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Alert, Button, Card, Col, Empty, Input, InputNumber, List, Row, Select, Space, Statistic, Table, Tag, Typography, Upload } from 'antd';
import { CheckCircleOutlined, DeleteOutlined, PlusOutlined, ReloadOutlined, UploadOutlined } from '@ant-design/icons';
import { Background, Handle, Position, ReactFlow, ReactFlowProvider, applyNodeChanges } from '@xyflow/react';
import type { Connection, Edge, Node, NodeChange, NodeProps } from '@xyflow/react';
import TopologyCanvas from '../components/canvas/TopologyCanvas';
import { flowchartApi } from '../services/api';
import { useAppStore } from '../stores/appStore';
import { useTopologyStore, type NodeData } from '../stores/topologyStore';
import type {
  DevicePortMetadata,
  FlowchartArtifact,
  FlowchartEditorStep,
  FlowchartEditorTransition,
  FlowchartTaskDiagram,
  PlcDiagnosticsResponse,
} from '../types';

const { Paragraph, Text, Title } = Typography;

const DEFAULT_ARTIFACT_URLS = [
  '/flowchart_review/flowchart.json',
  '/flowchart.json',
];

const MATERIAL_COLORS = [
  { fill: '#38bdf8', stroke: '#0369a1' },
  { fill: '#f97316', stroke: '#9a3412' },
  { fill: '#22c55e', stroke: '#166534' },
  { fill: '#eab308', stroke: '#854d0e' },
  { fill: '#a78bfa', stroke: '#5b21b6' },
  { fill: '#f43f5e', stroke: '#9f1239' },
];

interface ParsedEffect {
  kind: 'acquire' | 'transfer' | 'finish';
  from: string;
  to: string;
  label: string;
  taskName: string;
  effect: string;
}

interface FlowchartReviewPageProps {
  embedded?: boolean;
}

const FlowchartReviewPage: React.FC<FlowchartReviewPageProps> = ({ embedded = false }) => {
  const replaceTopology = useTopologyStore((state) => state.replaceTopology);
  const currentProject = useAppStore((state) => state.currentProject);
  const setCurrentProject = useAppStore((state) => state.setCurrentProject);
  const setHasUnsavedChanges = useAppStore((state) => state.setHasUnsavedChanges);
  const [artifact, setArtifact] = useState<FlowchartArtifact | null>(null);
  const [selectedTaskName, setSelectedTaskName] = useState<string | undefined>();
  const [loadState, setLoadState] = useState<'idle' | 'loading' | 'loaded' | 'missing' | 'error'>('idle');
  const [loadMessage, setLoadMessage] = useState<string>('');
  const [editorTaskName, setEditorTaskName] = useState('main_cycle');
  const [editorSteps, setEditorSteps] = useState<FlowchartEditorStep[]>([
    { id: 'start', label: 'Start', action: 'start cycle' },
    { id: 'complete', label: 'Complete', action: 'cycle complete' },
  ]);
  const [editorTransitions, setEditorTransitions] = useState<FlowchartEditorTransition[]>([
    { from: 'start', to: 'complete' },
  ]);
  const [generateState, setGenerateState] = useState<'idle' | 'running' | 'done' | 'error'>('idle');
  const [generateError, setGenerateError] = useState('');
  const [generatedSource, setGeneratedSource] = useState('');
  const [generatedDiagnostics, setGeneratedDiagnostics] = useState<PlcDiagnosticsResponse | null>(null);

  const loadDefaultArtifact = useCallback(async () => {
    setLoadState('loading');
    setLoadMessage('');
    for (const url of DEFAULT_ARTIFACT_URLS) {
      try {
        const response = await fetch(url, { cache: 'no-store' });
        if (!response.ok) {
          continue;
        }
        const nextArtifact = (await response.json()) as FlowchartArtifact;
        setArtifact(nextArtifact);
        setLoadState('loaded');
        setLoadMessage(`loaded ${url}`);
        return;
      } catch {
        // Try the next conventional location.
      }
    }
    setLoadState('missing');
    setLoadMessage('No bundled flowchart.json was found. Upload the artifact generated by rust_plc flowchart.');
  }, []);

  useEffect(() => {
    const timer = window.setTimeout(() => {
      void loadDefaultArtifact();
    }, 0);
    return () => window.clearTimeout(timer);
  }, [loadDefaultArtifact]);

  useEffect(() => {
    if (!artifact) {
      return;
    }
    const { nodes, edges } = flowchartTopologyToCanvas(artifact);
    replaceTopology(nodes, edges, false);
  }, [artifact, replaceTopology]);

  const taskOptions = useMemo(
    () => artifact?.tasks.map((task) => ({ value: task.task_name, label: task.task_name })) ?? [],
    [artifact?.tasks]
  );

  const selectedTask = useMemo(
    () => artifact?.tasks.find((task) => task.task_name === selectedTaskName) ?? artifact?.tasks[0],
    [artifact?.tasks, selectedTaskName]
  );

  const effects = useMemo(() => collectEffects(artifact), [artifact]);
  const forwardEffects = useMemo(() => effects.filter(isForwardMaterialEffect), [effects]);
  const pipelineSites = useMemo(() => collectPipelineSites(forwardEffects), [forwardEffects]);
  const summary = useMemo(() => summarizeArtifact(artifact), [artifact]);

  async function handleUpload(file: File) {
    try {
      const text = await file.text();
      const nextArtifact = JSON.parse(text) as FlowchartArtifact;
      setArtifact(nextArtifact);
      setLoadState('loaded');
      setLoadMessage(file.name);
    } catch (error) {
      setLoadState('error');
      setLoadMessage(error instanceof Error ? error.message : 'Invalid flowchart JSON');
    }
    return false;
  }

  async function handleGeneratePlc() {
    setGenerateState('running');
    setGenerateError('');
    try {
      const response = await flowchartApi.generatePlc({
        project_id: currentProject,
        task_name: editorTaskName,
        steps: editorSteps,
        transitions: editorTransitions,
      });
      setGeneratedSource(response.data.source);
      setGeneratedDiagnostics(response.data.diagnostics);
      setGenerateState('done');
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Flowchart PLC generation failed';
      setGenerateError(message);
      setGenerateState('error');
    }
  }

  function handleUseGeneratedSource() {
    if (!generatedSource) {
      return;
    }
    setCurrentProject('flowchart_generated', 'web-ui/generated-flowchart.plc', generatedSource);
    setHasUnsavedChanges(true);
  }

  return (
    <div style={{ padding: embedded ? 0 : 24, display: 'grid', gap: 18 }}>
      <Card
        style={{
          borderColor: '#164e63',
          background:
            'radial-gradient(circle at 10% 0%, rgba(56,189,248,0.18), transparent 32%), linear-gradient(135deg, #0f172a 0%, #111827 56%, #171717 100%)',
        }}
      >
        <Row gutter={[18, 18]} align="middle">
          <Col xs={24} xl={15}>
            <Space direction="vertical" size={8} style={{ width: '100%' }}>
              <Tag color="cyan">TS / Tailwind review surface</Tag>
              <Title level={2} style={{ margin: 0 }}>
                Flowchart Review Cockpit
              </Title>
              <Paragraph style={{ color: '#cbd5e1', marginBottom: 0, maxWidth: 900 }}>
                旧的 Web UI 是承载层。这里读取 CLI 生成的 flowchart artifact，把拓扑放回 React Flow 主画布，
                再把 system contract、并行物料波形、任务 SFC 和 effect reel 作为同一个审阅界面。
              </Paragraph>
              <Text type="secondary">{loadMessage}</Text>
            </Space>
          </Col>
          <Col xs={24} xl={9}>
            <Space wrap style={{ justifyContent: 'flex-end', width: '100%' }}>
              <Button icon={<ReloadOutlined />} onClick={loadDefaultArtifact} loading={loadState === 'loading'}>
                Reload bundled JSON
              </Button>
              <Upload beforeUpload={handleUpload} showUploadList={false} accept="application/json,.json">
                <Button type="primary" icon={<UploadOutlined />}>
                  Upload flowchart.json
                </Button>
              </Upload>
            </Space>
          </Col>
        </Row>
      </Card>

      <FlowchartEditorPanel
        taskName={editorTaskName}
        steps={editorSteps}
        transitions={editorTransitions}
        generatedSource={generatedSource}
        diagnostics={generatedDiagnostics}
        generateState={generateState}
        generateError={generateError}
        onTaskNameChange={setEditorTaskName}
        onStepsChange={setEditorSteps}
        onTransitionsChange={setEditorTransitions}
        onGenerate={handleGeneratePlc}
        onUseGeneratedSource={handleUseGeneratedSource}
      />

      {!artifact ? (
        <Card>
          {loadState === 'error' && <Alert type="error" message="Flowchart JSON load failed" description={loadMessage} showIcon />}
          {loadState !== 'error' && (
            <Empty
              description="No flowchart artifact is loaded yet."
              image={Empty.PRESENTED_IMAGE_SIMPLE}
            />
          )}
        </Card>
      ) : (
        <>
          <Row gutter={[18, 18]}>
            <Col xs={24} xl={6}>
              <MetricCard title="Tasks" value={summary.taskCount} />
            </Col>
            <Col xs={24} xl={6}>
              <MetricCard title="Steps" value={summary.stepCount} />
            </Col>
            <Col xs={24} xl={6}>
              <MetricCard title="Transitions" value={summary.transitionCount} />
            </Col>
            <Col xs={24} xl={6}>
              <MetricCard title="Topology Links" value={artifact.topology.link_count} />
            </Col>
          </Row>

          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'minmax(520px, 1.12fr) minmax(460px, 0.88fr)',
              gap: 18,
              minHeight: 620,
            }}
          >
            <Card
              title="Recovered Topology Canvas"
              extra={<Tag color="blue">{artifact.topology.device_count} devices</Tag>}
              styles={{ body: { height: 640, padding: 0 } }}
            >
              <TopologyCanvas readOnly showReadOnlyNotice={false} />
            </Card>

            <Space direction="vertical" size={18} style={{ width: '100%' }}>
              <Card title="System Contract">
                {artifact.system_contract ? (
                  <Space direction="vertical" size={8} style={{ width: '100%' }}>
                    <Text code>{artifact.system_contract.path}</Text>
                    <Text type="secondary">{artifact.system_contract.byte_count} bytes</Text>
                    <pre style={contractPreStyle}>{artifact.system_contract.excerpt}</pre>
                  </Space>
                ) : (
                  <Alert
                    type="warning"
                    showIcon
                    message="No system contract was found beside the PLC bundle."
                  />
                )}
              </Card>

              <Card title="Task Inventory">
                <Select
                  value={selectedTask?.task_name}
                  options={taskOptions}
                  onChange={setSelectedTaskName}
                  style={{ width: '100%', marginBottom: 12 }}
                  showSearch
                />
                {selectedTask && <TaskSummary task={selectedTask} />}
              </Card>
            </Space>
          </div>

          <Card title="Parallel Material Occupancy Map">
            <PipelineMap sites={pipelineSites} effects={forwardEffects} />
          </Card>

          <Row gutter={[18, 18]}>
            <Col xs={24} xl={12}>
              <Card title="Effect Reel">
                <List
                  size="small"
                  dataSource={effects.slice(0, 24)}
                  renderItem={(item, index) => (
                    <List.Item>
                      <Space direction="vertical" size={2}>
                        <Text>
                          <Tag color={effectTagColor(item.kind)}>{index + 1}</Tag>
                          {item.label}
                        </Text>
                        <Text type="secondary">{item.taskName} / {item.effect}</Text>
                      </Space>
                    </List.Item>
                  )}
                />
              </Card>
            </Col>
            <Col xs={24} xl={12}>
              <Card title="Topology Ledger">
                <Table
                  size="small"
                  pagination={{ pageSize: 8, size: 'small' }}
                  dataSource={artifact.topology.links.map((link, index) => ({ key: index, link }))}
                  columns={[{ title: 'Link', dataIndex: 'link' }]}
                />
              </Card>
            </Col>
          </Row>
        </>
      )}
    </div>
  );
};

interface FlowchartEditorPanelProps {
  taskName: string;
  steps: FlowchartEditorStep[];
  transitions: FlowchartEditorTransition[];
  generatedSource: string;
  diagnostics: PlcDiagnosticsResponse | null;
  generateState: 'idle' | 'running' | 'done' | 'error';
  generateError: string;
  onTaskNameChange: (taskName: string) => void;
  onStepsChange: (steps: FlowchartEditorStep[]) => void;
  onTransitionsChange: (transitions: FlowchartEditorTransition[]) => void;
  onGenerate: () => void;
  onUseGeneratedSource: () => void;
}

type FlowchartEditorNode = Node<{ label: string; action: string }>;

const flowchartEditorNodeTypes = {
  flowStep: FlowchartEditorNodeCard,
};

const FlowchartEditorPanel: React.FC<FlowchartEditorPanelProps> = ({
  taskName,
  steps,
  transitions,
  generatedSource,
  diagnostics,
  generateState,
  generateError,
  onTaskNameChange,
  onStepsChange,
  onTransitionsChange,
  onGenerate,
  onUseGeneratedSource,
}) => {
  const [nodePositions, setNodePositions] = useState<Record<string, { x: number; y: number }>>({});
  const editorCanvasRef = useRef<HTMLDivElement | null>(null);
  const editorCanvasVisibleRef = useRef(false);
  const [editorCanvasRevision, setEditorCanvasRevision] = useState(0);

  useEffect(() => {
    const element = editorCanvasRef.current;
    if (!element) {
      return undefined;
    }
    const observer = new ResizeObserver(([entry]) => {
      const visible = entry.contentRect.width > 0 && entry.contentRect.height > 0;
      if (visible && !editorCanvasVisibleRef.current) {
        setEditorCanvasRevision((revision) => revision + 1);
      }
      editorCanvasVisibleRef.current = visible;
    });
    observer.observe(element);
    return () => observer.disconnect();
  }, []);

  const defaultNextByStep = useMemo(() => {
    const map = new Map<string, string>();
    transitions
      .filter((transition) => !transition.guard?.trim())
      .forEach((transition) => map.set(transition.from, transition.to));
    return map;
  }, [transitions]);

  const guardedByStep = useMemo(() => {
    const map = new Map<string, FlowchartEditorTransition[]>();
    transitions
      .filter((transition) => transition.guard !== undefined)
      .forEach((transition) => {
        map.set(transition.from, [...(map.get(transition.from) ?? []), transition]);
      });
    return map;
  }, [transitions]);

  const editorNodes = useMemo<FlowchartEditorNode[]>(() => {
    return steps.map((step, index) => ({
      id: step.id,
      type: 'flowStep',
      position: nodePositions[step.id] ?? defaultEditorNodePosition(index),
      width: 170,
      height: step.action || step.delay_ms ? 76 : 60,
      data: {
        label: step.label || step.id,
        action: step.delay_ms
          ? `${step.action || ''} / ${step.delay_ms}ms`
          : step.action || '',
      },
    }));
  }, [nodePositions, steps]);

  const handleEditorNodesChange = useCallback((changes: NodeChange<FlowchartEditorNode>[]) => {
    setNodePositions((current) => {
      const currentNodes = steps.map((step, index) => ({
        id: step.id,
        position: current[step.id] ?? defaultEditorNodePosition(index),
        data: { label: step.label || step.id, action: step.action || '' },
      }));
      const changedNodes = applyNodeChanges(changes, currentNodes);
      const next = { ...current };
      changedNodes.forEach((node) => {
        next[node.id] = node.position;
      });
      return next;
    });
  }, [steps]);

  const handleEditorConnect = useCallback((connection: Connection) => {
    if (!connection.source || !connection.target || connection.source === connection.target) {
      return;
    }
    if (!steps.some((step) => step.id === connection.source) ||
      !steps.some((step) => step.id === connection.target)
    ) {
      return;
    }
    const exists = transitions.some((transition) =>
      transition.from === connection.source &&
      transition.to === connection.target &&
      transition.guard === undefined
    );
    if (exists) {
      return;
    }
    onTransitionsChange([
      ...transitions,
      { from: connection.source, to: connection.target },
    ]);
  }, [onTransitionsChange, steps, transitions]);

  function resetEditorLayout() {
    setNodePositions(Object.fromEntries(
      steps.map((step, index) => [step.id, defaultEditorNodePosition(index)])
    ));
  }

  function updateStep(index: number, patch: Partial<FlowchartEditorStep>) {
    const current = steps[index];
    if (!current) {
      return;
    }
    const nextStep = { ...current, ...patch };
    const nextSteps = steps.map((step, stepIndex) => (stepIndex === index ? nextStep : step));
    onStepsChange(nextSteps);

    if (patch.id !== undefined && patch.id !== current.id) {
      setNodePositions((positions) => {
        const existing = positions[current.id];
        if (!existing) {
          return positions;
        }
        const next = { ...positions };
        delete next[current.id];
        next[patch.id ?? current.id] = existing;
        return next;
      });
      onTransitionsChange(
        transitions.map((transition) => ({
          ...transition,
          from: transition.from === current.id ? patch.id ?? current.id : transition.from,
          to: transition.to === current.id ? patch.id ?? current.id : transition.to,
        }))
      );
    }
  }

  function addStep() {
    const id = uniqueClientStepId(steps);
    const previous = steps.at(-1)?.id;
    onStepsChange([...steps, { id, label: `Step ${steps.length + 1}`, action: `run step ${steps.length + 1}` }]);
    if (previous) {
      onTransitionsChange([...transitions.filter((transition) => transition.from !== previous), { from: previous, to: id }]);
    }
  }

  function removeStep(id: string) {
    if (steps.length <= 1) {
      return;
    }
    onStepsChange(steps.filter((step) => step.id !== id));
    onTransitionsChange(transitions.filter((transition) => transition.from !== id && transition.to !== id));
  }

  function setDefaultStep(from: string, to?: string) {
    const withoutCurrent = transitions.filter((transition) => transition.from !== from || transition.guard !== undefined);
    if (!to) {
      onTransitionsChange(withoutCurrent);
      return;
    }
    onTransitionsChange([...withoutCurrent, { from, to }]);
  }

  function addGuardedStep(from: string) {
    const target = steps.find((candidate) => candidate.id !== from)?.id;
    if (!target) {
      return;
    }
    onTransitionsChange([...transitions, { from, to: target, guard: 'true == true' }]);
  }

  function updateGuardedStep(from: string, guardedIndex: number, patch: { to?: string; guard?: string }) {
    let seen = -1;
    onTransitionsChange(
      transitions.map((transition) => {
        if (transition.from !== from || transition.guard === undefined) {
          return transition;
        }
        seen += 1;
        if (seen !== guardedIndex) {
          return transition;
        }
        return {
          ...transition,
          to: patch.to ?? transition.to,
          guard: patch.guard ?? transition.guard,
        };
      })
    );
  }

  function removeGuardedStep(from: string, guardedIndex: number) {
    let seen = -1;
    onTransitionsChange(
      transitions.filter((transition) => {
        if (transition.from !== from || transition.guard === undefined) {
          return true;
        }
        seen += 1;
        return seen !== guardedIndex;
      })
    );
  }

  function connectSequentially() {
    onTransitionsChange(
      steps.slice(0, -1).map((step, index) => ({
        from: step.id,
        to: steps[index + 1].id,
      }))
    );
  }

  function removeTransitionByIndex(index: number) {
    onTransitionsChange(transitions.filter((_, transitionIndex) => transitionIndex !== index));
  }

  const status = diagnostics
    ? diagnostics.valid
      ? { type: 'success' as const, label: 'Generated PLC passed diagnostics' }
      : { type: 'error' as const, label: `Generated PLC failed at ${diagnostics.stage}` }
    : null;

  return (
    <Card
      title="Visual PLC Flow Editor"
      extra={
        <Space wrap>
          <Button icon={<PlusOutlined />} onClick={addStep}>
            Add step
          </Button>
          <Button onClick={connectSequentially}>Connect sequentially</Button>
          <Button onClick={resetEditorLayout}>Reset layout</Button>
          <Button type="primary" loading={generateState === 'running'} onClick={onGenerate}>
            Generate PLC
          </Button>
        </Space>
      }
    >
      <div style={editorGridStyle}>
        <div ref={editorCanvasRef} style={editorCanvasShellStyle}>
          <EditorTransitionOverlay
            steps={steps}
            transitions={transitions}
            nodePositions={nodePositions}
            onRemoveTransition={removeTransitionByIndex}
          />
          <ReactFlowProvider>
            <ReactFlow
              key={`flow-editor-${editorCanvasRevision}`}
              nodes={editorNodes}
              edges={[]}
              onNodesChange={handleEditorNodesChange}
              onConnect={handleEditorConnect}
              nodeTypes={flowchartEditorNodeTypes}
              defaultViewport={{ x: 0, y: 0, zoom: 1 }}
              minZoom={1}
              maxZoom={1}
              nodesDraggable
              nodesConnectable
              elementsSelectable
              panOnDrag={false}
              zoomOnScroll={false}
              zoomOnPinch={false}
              zoomOnDoubleClick={false}
              connectionLineStyle={{ stroke: '#2563eb', strokeWidth: 1.8 }}
            >
              <Background gap={18} size={1} color="#334155" />
            </ReactFlow>
          </ReactFlowProvider>
        </div>

        <Space direction="vertical" size={12} style={{ width: '100%', minWidth: 0 }}>
          <label style={fieldLabelStyle} htmlFor="flowchart-task-name">Task name</label>
          <Input
            id="flowchart-task-name"
            value={taskName}
            onChange={(event) => onTaskNameChange(event.target.value)}
            placeholder="main_cycle"
          />

          <List
            size="small"
            dataSource={steps}
            locale={{ emptyText: 'Add a step to generate PLC source.' }}
            renderItem={(step, index) => (
              <List.Item
                actions={[
                  <Button
                    key="delete"
                    icon={<DeleteOutlined />}
                    disabled={steps.length <= 1}
                    onClick={() => removeStep(step.id)}
                    aria-label={`Delete ${step.id}`}
                  />,
                ]}
              >
                <Space direction="vertical" size={8} style={{ width: '100%' }}>
                  <Space wrap align="start" style={{ width: '100%' }}>
                    <Input
                      value={step.id}
                      onChange={(event) => updateStep(index, { id: event.target.value })}
                      placeholder="step_id"
                      style={{ width: 150 }}
                    />
                    <Input
                      value={step.label}
                      onChange={(event) => updateStep(index, { label: event.target.value })}
                      placeholder="Step label"
                      style={{ width: 180 }}
                    />
                    <Select
                      allowClear
                      value={defaultNextByStep.get(step.id)}
                      placeholder="Default next"
                      style={{ width: 170 }}
                      options={steps
                        .filter((candidate) => candidate.id !== step.id)
                        .map((candidate) => ({ value: candidate.id, label: candidate.label || candidate.id }))}
                      onChange={(value) => setDefaultStep(step.id, value)}
                    />
                    <Button
                      icon={<PlusOutlined />}
                      onClick={() => addGuardedStep(step.id)}
                      disabled={steps.length <= 1}
                    >
                      Add condition
                    </Button>
                  </Space>
                  <div style={stepActionRowStyle}>
                    <Input
                      value={step.action}
                      onChange={(event) => updateStep(index, { action: event.target.value })}
                      placeholder="Action log text"
                      style={{ minWidth: 180, flex: '1 1 260px' }}
                    />
                    <InputNumber
                      min={0}
                      max={3600000}
                      step={10}
                      precision={0}
                      value={step.delay_ms}
                      onChange={(value) =>
                        updateStep(index, {
                          delay_ms: typeof value === 'number' && value > 0 ? value : undefined,
                        })
                      }
                      placeholder="Delay"
                      addonAfter="ms"
                      style={{ width: 150 }}
                    />
                  </div>
                  {(guardedByStep.get(step.id) ?? []).length > 0 && (
                    <div style={guardRowsStyle}>
                      {(guardedByStep.get(step.id) ?? []).map((transition, guardedIndex) => (
                        <div
                          key={`${step.id}-${guardedIndex}-${transition.to}`}
                          style={guardRowStyle}
                        >
                          <Select
                            value={transition.to}
                            placeholder="Conditional next"
                            style={{ minWidth: 150, flex: '0 0 150px' }}
                            options={steps
                              .filter((candidate) => candidate.id !== step.id)
                              .map((candidate) => ({ value: candidate.id, label: candidate.label || candidate.id }))}
                            onChange={(value) => updateGuardedStep(step.id, guardedIndex, { to: value })}
                          />
                          <Input
                            value={transition.guard ?? ''}
                            onChange={(event) => updateGuardedStep(step.id, guardedIndex, { guard: event.target.value })}
                            placeholder="Guard expression"
                            style={{ minWidth: 180, flex: '1 1 220px' }}
                          />
                          <Button
                            icon={<DeleteOutlined />}
                            onClick={() => removeGuardedStep(step.id, guardedIndex)}
                            aria-label={`Delete condition ${guardedIndex + 1} from ${step.id}`}
                          />
                        </div>
                      ))}
                    </div>
                  )}
                </Space>
              </List.Item>
            )}
          />
        </Space>
      </div>

      <div style={editorResultGridStyle}>
        <Space direction="vertical" size={8} style={{ width: '100%' }}>
          {generateState === 'error' && <Alert type="error" showIcon message="Generation request failed" description={generateError} />}
          {status && (
            <Alert
              type={status.type}
              showIcon
              icon={status.type === 'success' ? <CheckCircleOutlined /> : undefined}
              message={status.label}
              description={
                diagnostics
                  ? `${diagnostics.summary.tasks} task, ${diagnostics.summary.states} states, ${diagnostics.summary.transitions} transitions`
                  : undefined
              }
            />
          )}
          {diagnostics && diagnostics.issues.length > 0 && (
            <List
              size="small"
              bordered
              dataSource={diagnostics.issues.slice(0, 5)}
              renderItem={(issue) => (
                <List.Item>
                  <Space direction="vertical" size={2}>
                    <Text>
                      <Tag color={issue.severity === 'error' ? 'red' : 'gold'}>{issue.stage}</Tag>
                      {issue.message}
                    </Text>
                    {issue.suggestion && <Text type="secondary">{issue.suggestion}</Text>}
                  </Space>
                </List.Item>
              )}
            />
          )}
        </Space>

        <Space direction="vertical" size={8} style={{ width: '100%' }}>
          <Input.TextArea
            value={generatedSource}
            readOnly
            autoSize={{ minRows: 8, maxRows: 14 }}
            placeholder="Generated PLC source appears here after diagnostics run."
            style={{ fontFamily: 'Cascadia Code, Consolas, monospace', fontSize: 12 }}
          />
          <Button disabled={!generatedSource || !diagnostics?.valid} onClick={onUseGeneratedSource}>
            Use in PLC editor
          </Button>
        </Space>
      </div>
    </Card>
  );
};

const EditorTransitionOverlay: React.FC<{
  steps: FlowchartEditorStep[];
  transitions: FlowchartEditorTransition[];
  nodePositions: Record<string, { x: number; y: number }>;
  onRemoveTransition: (index: number) => void;
}> = ({ steps, transitions, nodePositions, onRemoveTransition }) => {
  const stepById = useMemo(() => new Map(steps.map((step, index) => [step.id, { step, index }])), [steps]);

  return (
    <svg aria-hidden="true" style={editorTransitionOverlayStyle}>
      {transitions.map((transition, index) => {
        const source = stepById.get(transition.from);
        const target = stepById.get(transition.to);
        if (!source || !target || transition.from === transition.to) {
          return null;
        }
        const sourcePosition = nodePositions[transition.from] ?? defaultEditorNodePosition(source.index);
        const targetPosition = nodePositions[transition.to] ?? defaultEditorNodePosition(target.index);
        const sourceHeight = editorNodeHeight(source.step);
        const sourceX = sourcePosition.x + EDITOR_NODE_WIDTH / 2;
        const sourceY = sourcePosition.y + sourceHeight;
        const targetX = targetPosition.x + EDITOR_NODE_WIDTH / 2;
        const targetY = targetPosition.y;
        const verticalOffset = Math.max(36, Math.abs(targetY - sourceY) / 2);
        const path = `M ${sourceX} ${sourceY} C ${sourceX} ${sourceY + verticalOffset}, ${targetX} ${targetY - verticalOffset}, ${targetX} ${targetY}`;
        const stroke = transition.guard !== undefined ? '#f97316' : '#2563eb';

        return (
          <g key={`${transition.from}-${transition.to}-${index}`}>
            <path
              d={path}
              fill="none"
              stroke={stroke}
              strokeWidth={2}
              strokeLinecap="round"
              style={{ pointerEvents: 'none' }}
            />
            <path
              d={path}
              fill="none"
              stroke="transparent"
              strokeWidth={14}
              strokeLinecap="round"
              role="button"
              tabIndex={0}
              aria-label={`Delete transition ${transition.from} to ${transition.to}`}
              style={{ cursor: 'pointer', pointerEvents: 'stroke' }}
              onClick={() => onRemoveTransition(index)}
              onKeyDown={(event) => {
                if (event.key === 'Enter' || event.key === ' ') {
                  event.preventDefault();
                  onRemoveTransition(index);
                }
              }}
            />
            {transition.guard?.trim() && (
              <text
                x={(sourceX + targetX) / 2}
                y={(sourceY + targetY) / 2 - 6}
                textAnchor="middle"
                style={editorTransitionLabelStyle}
              >
                {transition.guard.trim()}
              </text>
            )}
          </g>
        );
      })}
    </svg>
  );
};

function FlowchartEditorNodeCard({ data }: NodeProps<FlowchartEditorNode>) {
  return (
    <div style={editorNodeCardStyle}>
      <Handle id="in" type="target" position={Position.Top} style={editorNodeHandleStyle} />
      <Text strong style={editorNodeTitleStyle}>{data.label}</Text>
      {data.action && <Text style={editorNodeActionStyle}>{data.action}</Text>}
      <Handle id="out" type="source" position={Position.Bottom} style={editorNodeHandleStyle} />
    </div>
  );
}

function uniqueClientStepId(steps: FlowchartEditorStep[]): string {
  const used = new Set(steps.map((step) => step.id));
  for (let index = steps.length + 1; ; index += 1) {
    const candidate = `step_${index}`;
    if (!used.has(candidate)) {
      return candidate;
    }
  }
}

function defaultEditorNodePosition(index: number) {
  return { x: 80 + index * 220, y: index % 2 === 0 ? 90 : 190 };
}

function editorNodeHeight(step: FlowchartEditorStep) {
  return step.action || step.delay_ms ? 76 : 60;
}

const MetricCard: React.FC<{ title: string; value: number }> = ({ title, value }) => (
  <Card>
    <Statistic title={title} value={value} />
  </Card>
);

const TaskSummary: React.FC<{ task: FlowchartTaskDiagram }> = ({ task }) => (
  <Space direction="vertical" size={12} style={{ width: '100%' }}>
    <Space wrap>
      <Tag color="geekblue">{task.steps.length} steps</Tag>
      <Tag color="purple">{task.transitions.length} transitions</Tag>
      <Tag color={taskRoleColor(task.task_name)}>{taskRole(task.task_name)}</Tag>
    </Space>
    <div style={sfcStripStyle}>
      {task.steps.map((step, index) => (
        <React.Fragment key={step.step_name}>
          <div style={sfcStepStyle} title={step.statements.join('\n')}>
            <Text strong>{step.step_name}</Text>
            <Text type="secondary" style={{ fontSize: 11 }}>
              {shortSource(step.source)}:{step.line}
            </Text>
          </div>
          {index < task.steps.length - 1 && <div style={sfcTransitionStyle}>T</div>}
        </React.Fragment>
      ))}
    </div>
    <List
      size="small"
      dataSource={task.transitions.slice(0, 10)}
      renderItem={(transition) => (
        <List.Item>
          <Space direction="vertical" size={2}>
            <Text>{`${transition.from_step} -> ${transition.to_step}`}</Text>
            <Text type="secondary">{transition.guard}</Text>
          </Space>
        </List.Item>
      )}
    />
  </Space>
);

const PipelineMap: React.FC<{ sites: string[]; effects: ParsedEffect[] }> = ({ sites, effects }) => {
  if (sites.length === 0) {
    return <Empty description="No forward workpiece effects were available for pipeline projection." />;
  }

  const width = Math.max(980, sites.length * 170);
  const left = 80;
  const right = width - 80;
  const y = 105;
  const xFor = (index: number) => left + (sites.length <= 1 ? 0 : (index * (right - left)) / (sites.length - 1));
  const indexBySite = new Map(sites.map((site, index) => [site, index]));

  return (
    <div style={{ overflowX: 'auto', borderRadius: 14, background: '#020617', border: '1px solid #1e293b' }}>
      <svg width={width} height={260} role="img" aria-label="parallel material occupancy map">
        <defs>
          <marker id="flowArrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto">
            <path d="M0,0 L8,4 L0,8 z" fill="#64748b" />
          </marker>
        </defs>
        <text x={left} y={36} fill="#93c5fd" fontFamily="Cascadia Code, Consolas, monospace" fontSize="13">
          steady-state multi-wafer projection
        </text>
        <text x={left} y={56} fill="#94a3b8" fontFamily="Cascadia Code, Consolas, monospace" fontSize="11">
          colors indicate different wafers occupying nearby stations, not one serial wafer path
        </text>
        <line x1={left} y1={y} x2={right} y2={y} stroke="#334155" strokeWidth="5" strokeLinecap="round" />
        {effects.map((effect, index) => {
          const from = indexBySite.get(effect.from);
          const to = indexBySite.get(effect.to);
          if (from === undefined || to === undefined) {
            return null;
          }
          return (
            <line
              key={`${effect.taskName}-${effect.effect}-${index}`}
              x1={xFor(from)}
              y1={y}
              x2={xFor(to)}
              y2={y}
              stroke="#64748b"
              strokeWidth="2"
              markerEnd="url(#flowArrow)"
              opacity={0.72}
            />
          );
        })}
        {sites.map((site, index) => {
          const color = MATERIAL_COLORS[index % MATERIAL_COLORS.length];
          const x = xFor(index);
          return (
            <g key={site}>
              <circle cx={x} cy={y} r="17" fill={color.fill} stroke={color.stroke} strokeWidth="2" />
              <text x={x} y={y + 4} textAnchor="middle" fill="#0f172a" fontWeight="700" fontSize="11">
                W{index + 1}
              </text>
              <text x={x} y={y + 48} textAnchor="middle" fill="#e2e8f0" fontSize="11" fontFamily="Cascadia Code, Consolas, monospace">
                {compactSite(site)}
              </text>
              <title>{site}</title>
            </g>
          );
        })}
      </svg>
    </div>
  );
};

// eslint-disable-next-line react-refresh/only-export-components
export function flowchartTopologyToCanvas(artifact: FlowchartArtifact): { nodes: Node<NodeData>[]; edges: Edge[] } {
  const linkRows = artifact.topology.links.map(parseTopologyLink).filter((item): item is ParsedLink => Boolean(item));
  const nodeNames = new Set<string>();

  (artifact.topology.devices ?? []).forEach((device) => nodeNames.add(device.split(':')[0]));
  linkRows.forEach((link) => {
    nodeNames.add(link.from);
    nodeNames.add(link.to);
  });

  const layout = buildIndustrialTopologyLayout(Array.from(nodeNames), linkRows, [], artifact);
  const nodes: Node<NodeData>[] = layout.names.map((name) => {
    const stage = layout.stageByName.get(name) ?? stageName(name);
    const lane = layout.laneByName.get(name) ?? laneForName(name, artifact);
    const nodeType = nodeTypeForName(name);
    return {
      id: name,
      type: nodeType,
      position: layout.positions.get(name) ?? { x: 0, y: 0 },
      data: {
        label: name,
        type: nodeType,
        status: isWorkpieceEndpoint(name, artifact) ? 'active' : 'idle',
        device_type: stage,
        layout_lane: lane,
        ports: portsForNode(nodeType),
        tags: {
          functional_group: [stage.toLowerCase()],
          danger_level: lane === 'material' ? ['workpiece'] : [],
          location_group: [`flowchart/${stage.toLowerCase()}`, `flowchart/${stage.toLowerCase()}/${lane}`],
        },
      },
    };
  });

  const edges: Edge[] = [
    ...linkRows.map((link, index) => ({
      id: `flowchart-link-${index}`,
      source: link.from,
      target: link.to,
      sourceHandle: sourceHandleForNode(link.from),
      targetHandle: targetHandleForNode(link.to),
      label: undefined,
      data: { relation: link.relation, hideLabel: true },
      style: {
        stroke: relationColor(link.relation),
        strokeWidth: 1.8,
      },
    })),
  ];

  return { nodes, edges };
}

type TopologyLane = 'material' | 'actuator' | 'command' | 'feedback' | 'io' | 'system';

interface TopologyLayout {
  names: string[];
  positions: Map<string, { x: number; y: number }>;
  stageByName: Map<string, string>;
  laneByName: Map<string, TopologyLane>;
}

const STAGE_ORDER = ['FEED', 'SLIDE', 'ARM', 'ORIENT', 'TRANSFER', 'MEASURE', 'REJECT', 'IO', 'SYSTEM'];
const LANE_Y: Record<TopologyLane, number> = {
  material: 70,
  actuator: 205,
  command: 395,
  feedback: 585,
  io: 860,
  system: 1100,
};

const COMMAND_ACTUATOR_PATTERN = /(^|_)vac_.*_valve$|^vac_.*valve$|_vac_valve$/i;
const CONTROL_CHAIN_X = {
  output: -430,
  command: -225,
  actuator: 0,
  feedback: 250,
  input: 470,
} as const;
const CONTROL_CHAIN_START_Y = 210;
const CONTROL_CHAIN_ITEM_GAP = 118;
const CONTROL_CHAIN_BLOCK_GAP = 76;
const CONTROL_CHAIN_MIN_BLOCK_HEIGHT = 136;
const GENERIC_GRID_X_GAP = 170;
const GENERIC_GRID_Y_GAP = 132;

function buildIndustrialTopologyLayout(
  names: string[],
  links: ParsedLink[],
  materialEffects: ParsedEffect[],
  artifact: FlowchartArtifact
): TopologyLayout {
  const adjacency = buildAdjacency(links, materialEffects);
  const stageByName = inferConnectedStages(names, links, materialEffects);
  const laneByName = new Map(names.map((name) => [name, laneForName(name, artifact)]));

  const grouped = new Map<string, Map<TopologyLane, string[]>>();
  names.forEach((name) => {
    const stage = stageByName.get(name) ?? stageName(name);
    const lane = laneByName.get(name) ?? 'system';
    if (!grouped.has(stage)) {
      grouped.set(stage, new Map());
    }
    const stageGroup = grouped.get(stage)!;
    stageGroup.set(lane, [...(stageGroup.get(lane) ?? []), name]);
  });

  const activeStages = STAGE_ORDER.filter((stage) => grouped.has(stage));
  const positions = new Map<string, { x: number; y: number }>();
  const orderedNames: string[] = [];
  const stageX = new Map<string, number>();
  const stageWidth = new Map<string, number>();

  activeStages.forEach((stage) => {
    const stageGroup = grouped.get(stage)!;
    const maxLaneCount = Math.max(...Array.from(stageGroup.values()).map((items) => items.length), 1);
    const laneColumnCount = Math.min(7, Math.max(1, Math.ceil(Math.sqrt(maxLaneCount * 1.7))));
    const couplingRootCount = couplingRootsForStage(stageGroup).length;
    const hasFeedbackTerminalPairs =
      (stageGroup.get('feedback')?.length ?? 0) > 0 && (stageGroup.get('io')?.length ?? 0) > 0;
    stageWidth.set(stage, Math.max(couplingRootCount > 0 || hasFeedbackTerminalPairs ? 1120 : 560, 260 + laneColumnCount * GENERIC_GRID_X_GAP));
  });

  activeStages.reduce((cursor, stage) => {
    stageX.set(stage, cursor + (stageWidth.get(stage) ?? 340) / 2);
    return cursor + (stageWidth.get(stage) ?? 340) + 160;
  }, 120);

  activeStages.forEach((stage) => {
    const stageGroup = grouped.get(stage)!;
    const xCenter = stageX.get(stage) ?? 120;
    const availableWidth = Math.max(220, (stageWidth.get(stage) ?? 340) - 120);
    const horizontalStep = GENERIC_GRID_X_GAP;
    const verticalStep = GENERIC_GRID_Y_GAP;

    (Object.keys(LANE_Y) as TopologyLane[]).forEach((lane) => {
      const laneItems = (stageGroup.get(lane) ?? []).sort((left, right) =>
        layoutOrderKey(left, adjacency, stageX, stageByName).localeCompare(layoutOrderKey(right, adjacency, stageX, stageByName))
      );
      const columnCount = Math.max(
        1,
        Math.min(
          laneItems.length,
          Math.max(1, Math.floor(availableWidth / horizontalStep))
        )
      );
      const gridWidth = (columnCount - 1) * horizontalStep;
      laneItems.forEach((name, index) => {
        const col = index % columnCount;
        const row = Math.floor(index / columnCount);
        positions.set(name, {
          x: xCenter - gridWidth / 2 + col * horizontalStep,
          y: LANE_Y[lane] + row * verticalStep,
        });
        orderedNames.push(name);
      });
    });
  });

  applyActuatorCouplingLayout({
    activeStages,
    grouped,
    links,
    positions,
    stageX,
    stageWidth,
    laneByName,
  });

  return { names: orderedNames, positions, stageByName, laneByName };
}

interface CouplingLayoutContext {
  activeStages: string[];
  grouped: Map<string, Map<TopologyLane, string[]>>;
  links: ParsedLink[];
  positions: Map<string, { x: number; y: number }>;
  stageX: Map<string, number>;
  stageWidth: Map<string, number>;
  laneByName: Map<string, TopologyLane>;
}

function applyActuatorCouplingLayout(ctx: CouplingLayoutContext) {
  const incoming = new Map<string, ParsedLink[]>();
  const outgoing = new Map<string, ParsedLink[]>();
  ctx.links.forEach((link) => {
    incoming.set(link.to, [...(incoming.get(link.to) ?? []), link]);
    outgoing.set(link.from, [...(outgoing.get(link.from) ?? []), link]);
  });

  ctx.activeStages.forEach((stage) => {
    const stageGroup = ctx.grouped.get(stage);
    const actuators = couplingRootsForStage(stageGroup)
      .filter((name) => hasCouplingEdges(name, incoming, outgoing, ctx.laneByName))
      .sort();

    if (!stageGroup) {
      return;
    }

    const xCenter = ctx.stageX.get(stage) ?? 120;
    const assigned = new Set<string>();
    const x = {
      output: xCenter + CONTROL_CHAIN_X.output,
      command: xCenter + CONTROL_CHAIN_X.command,
      actuator: xCenter + CONTROL_CHAIN_X.actuator,
      feedback: xCenter + CONTROL_CHAIN_X.feedback,
      input: xCenter + CONTROL_CHAIN_X.input,
    };
    let yCursor = CONTROL_CHAIN_START_Y;

    actuators.forEach((actuator) => {
      const commands = uniqueSorted([
        ...directPredecessors(actuator, incoming).filter((name) => ctx.laneByName.get(name) === 'command'),
      ]);
      const directOutputs = directPredecessors(actuator, incoming).filter((name) => ctx.laneByName.get(name) === 'io');
      const commandOutputs = commands.flatMap((command) =>
        directPredecessors(command, incoming).filter((name) => ctx.laneByName.get(name) === 'io')
      );
      const outputs = uniqueSorted([...directOutputs, ...commandOutputs]);
      const feedbacks = uniqueSorted(
        directSuccessors(actuator, outgoing).filter((name) => ctx.laneByName.get(name) === 'feedback')
      );
      const feedbackInputs = feedbacks.flatMap((feedback) =>
        directSuccessors(feedback, outgoing).filter((name) => ctx.laneByName.get(name) === 'io')
      );
      const inputs = uniqueSorted(feedbackInputs);
      const commandColumn = isCommandActuator(actuator) ? uniqueSorted([...commands, actuator]) : commands;
      const actuatorColumn = isCommandActuator(actuator) ? [] : [actuator];
      const maxColumnItems = Math.max(
        outputs.length,
        commandColumn.length,
        actuatorColumn.length,
        feedbacks.length,
        inputs.length,
        1
      );
      const blockHeight = Math.max(
        CONTROL_CHAIN_MIN_BLOCK_HEIGHT,
        56 + (maxColumnItems - 1) * CONTROL_CHAIN_ITEM_GAP
      );
      const yBase = yCursor + blockHeight / 2;

      setStackedPositions(ctx.positions, outputs, x.output, yBase, CONTROL_CHAIN_ITEM_GAP);
      setStackedPositions(ctx.positions, commandColumn, x.command, yBase, CONTROL_CHAIN_ITEM_GAP);
      setStackedPositions(ctx.positions, actuatorColumn, x.actuator, yBase, CONTROL_CHAIN_ITEM_GAP);
      setStackedPositions(ctx.positions, feedbacks, x.feedback, yBase, CONTROL_CHAIN_ITEM_GAP);
      setStackedPositions(ctx.positions, inputs, x.input, yBase, CONTROL_CHAIN_ITEM_GAP);
      [
        ...outputs,
        ...commandColumn,
        ...actuatorColumn,
        ...feedbacks,
        ...inputs,
      ].forEach((name) => assigned.add(name));
      yCursor += blockHeight + CONTROL_CHAIN_BLOCK_GAP;
    });

    const feedbackPairs = uniqueSorted(stageGroup.get('feedback') ?? [])
      .filter((feedback) => !assigned.has(feedback))
      .map((feedback) => ({
        feedback,
        inputs: uniqueSorted(
          directSuccessors(feedback, outgoing).filter((name) => ctx.laneByName.get(name) === 'io' && !assigned.has(name))
        ),
      }))
      .filter((pair) => pair.inputs.length > 0);

    feedbackPairs.forEach(({ feedback, inputs }) => {
      const maxColumnItems = Math.max(1, inputs.length);
      const blockHeight = Math.max(
        CONTROL_CHAIN_MIN_BLOCK_HEIGHT,
        56 + (maxColumnItems - 1) * CONTROL_CHAIN_ITEM_GAP
      );
      const yBase = yCursor + blockHeight / 2;
      ctx.positions.set(feedback, { x: x.feedback, y: yBase });
      setStackedPositions(ctx.positions, inputs, x.input, yBase, CONTROL_CHAIN_ITEM_GAP);
      assigned.add(feedback);
      inputs.forEach((name) => assigned.add(name));
      yCursor += blockHeight + CONTROL_CHAIN_BLOCK_GAP;
    });

    placeRemainingStageNodes({
      stageGroup,
      positions: ctx.positions,
      laneByName: ctx.laneByName,
      assigned,
      xCenter,
      yStart: Math.max(yCursor, CONTROL_CHAIN_START_Y + CONTROL_CHAIN_MIN_BLOCK_HEIGHT),
    });
  });
}

function placeRemainingStageNodes({
  stageGroup,
  positions,
  laneByName,
  assigned,
  xCenter,
  yStart,
}: {
  stageGroup: Map<TopologyLane, string[]>;
  positions: Map<string, { x: number; y: number }>;
  laneByName: Map<string, TopologyLane>;
  assigned: Set<string>;
  xCenter: number;
  yStart: number;
}) {
  const remaining = Array.from(new Set(Array.from(stageGroup.values()).flat()))
    .filter((name) => !assigned.has(name))
    .sort();
  const byLane = new Map<TopologyLane, string[]>();
  remaining.forEach((name) => {
    const lane = laneByName.get(name) ?? 'system';
    byLane.set(lane, [...(byLane.get(lane) ?? []), name]);
  });

  let yCursor = yStart;
  (['material', 'command', 'actuator', 'feedback', 'io', 'system'] as TopologyLane[]).forEach((lane) => {
    const items = byLane.get(lane) ?? [];
    if (items.length === 0) {
      return;
    }
    const xBase = xCenter + fallbackLaneOffset(lane, items);
    const columnCount = Math.min(3, Math.max(1, Math.ceil(Math.sqrt(items.length))));
    const gridWidth = (columnCount - 1) * GENERIC_GRID_X_GAP;
    items.forEach((name, index) => {
      const col = index % columnCount;
      const row = Math.floor(index / columnCount);
      positions.set(name, {
        x: xBase - gridWidth / 2 + col * GENERIC_GRID_X_GAP,
        y: yCursor + row * GENERIC_GRID_Y_GAP,
      });
    });
    yCursor += Math.ceil(items.length / columnCount) * GENERIC_GRID_Y_GAP + 48;
  });
}

function fallbackLaneOffset(lane: TopologyLane, names: string[]): number {
  if (lane === 'material') return 0;
  if (lane === 'command') return CONTROL_CHAIN_X.command;
  if (lane === 'actuator') return CONTROL_CHAIN_X.actuator;
  if (lane === 'feedback') return CONTROL_CHAIN_X.feedback;
  if (lane === 'io') {
    return names.some((name) => /^x\d+$/i.test(name)) && !names.some((name) => /^y\d+$/i.test(name))
      ? CONTROL_CHAIN_X.input
      : CONTROL_CHAIN_X.output;
  }
  return 0;
}

function couplingRootsForStage(stageGroup: Map<TopologyLane, string[]> | undefined): string[] {
  if (!stageGroup) {
    return [];
  }
  return [
    ...(stageGroup.get('actuator') ?? []),
    ...(stageGroup.get('command') ?? []).filter(isCommandActuator),
  ];
}

function isCommandActuator(name: string): boolean {
  return COMMAND_ACTUATOR_PATTERN.test(name.toLowerCase());
}

function hasCouplingEdges(
  name: string,
  incoming: Map<string, ParsedLink[]>,
  outgoing: Map<string, ParsedLink[]>,
  laneByName: Map<string, TopologyLane>
): boolean {
  return [
    ...directPredecessors(name, incoming),
    ...directSuccessors(name, outgoing),
  ].some((neighbor) => {
    const lane = laneByName.get(neighbor);
    return lane === 'command' || lane === 'feedback' || lane === 'io';
  });
}

function directPredecessors(name: string, incoming: Map<string, ParsedLink[]>): string[] {
  return (incoming.get(name) ?? []).map((link) => link.from);
}

function directSuccessors(name: string, outgoing: Map<string, ParsedLink[]>): string[] {
  return (outgoing.get(name) ?? []).map((link) => link.to);
}

function uniqueSorted(values: string[]): string[] {
  return Array.from(new Set(values)).sort();
}

function setStackedPositions(
  positions: Map<string, { x: number; y: number }>,
  names: string[],
  x: number,
  yCenter: number,
  step: number
) {
  if (names.length === 0) {
    return;
  }
  const firstY = yCenter - ((names.length - 1) * step) / 2;
  names.forEach((name, index) => {
    positions.set(name, { x, y: firstY + index * step });
  });
}

function buildAdjacency(links: ParsedLink[], materialEffects: ParsedEffect[]): Map<string, Set<string>> {
  const adjacency = new Map<string, Set<string>>();
  const connect = (left: string, right: string) => {
    if (!adjacency.has(left)) adjacency.set(left, new Set());
    if (!adjacency.has(right)) adjacency.set(right, new Set());
    adjacency.get(left)!.add(right);
    adjacency.get(right)!.add(left);
  };
  links.forEach((link) => connect(link.from, link.to));
  materialEffects.forEach((effect) => connect(effect.from, effect.to));
  return adjacency;
}

function inferConnectedStages(
  names: string[],
  links: ParsedLink[],
  materialEffects: ParsedEffect[]
): Map<string, string> {
  const inferred = new Map(names.map((name) => [name, stageName(name)]));
  const relationEdges = links.map((link) => [link.from, link.to] as const);
  const materialEdges = materialEffects.map((effect) => [effect.from, effect.to] as const);

  for (let pass = 0; pass < 3; pass += 1) {
    [...relationEdges, ...materialEdges].forEach(([from, to]) => {
      const fromStage = inferred.get(from) ?? stageName(from);
      const toStage = inferred.get(to) ?? stageName(to);
      if (fromStage === 'IO' && toStage !== 'IO' && toStage !== 'SYSTEM') {
        inferred.set(from, toStage);
      }
      if (toStage === 'IO' && fromStage !== 'IO' && fromStage !== 'SYSTEM') {
        inferred.set(to, fromStage);
      }
      if (fromStage === 'SYSTEM' && toStage !== 'SYSTEM') {
        inferred.set(from, toStage);
      }
      if (toStage === 'SYSTEM' && fromStage !== 'SYSTEM') {
        inferred.set(to, fromStage);
      }
    });
  }

  return inferred;
}

function laneForName(name: string, artifact: FlowchartArtifact): TopologyLane {
  const lower = name.toLowerCase();
  if (isWorkpieceEndpoint(name, artifact) || lower.includes('nozzle') || lower.includes('ejector')) return 'material';
  if (/^[xy]\d+$/i.test(name) || lower.includes('plc_main')) return 'io';
  if (lower.includes('sensor') || lower.includes('wafer_on') || lower.includes('ready') || lower.includes('detect')) return 'feedback';
  if (lower.includes('button') || lower.includes('mode_')) return 'feedback';
  if (lower.includes('valve') || lower.startsWith('y')) return 'command';
  if (lower.includes('cyl') || lower.includes('axis') || lower.includes('motor') || lower.includes('swing') || lower.includes('lift')) return 'actuator';
  return 'system';
}

function layoutOrderKey(
  name: string,
  adjacency: Map<string, Set<string>>,
  stageX: Map<string, number>,
  stageByName: Map<string, string>
): string {
  const neighbors = Array.from(adjacency.get(name) ?? []);
  if (neighbors.length === 0) {
    return `9999-${name}`;
  }
  const barycenter =
    neighbors.reduce((sum, neighbor) => sum + (stageX.get(stageByName.get(neighbor) ?? stageName(neighbor)) ?? 0), 0) /
    neighbors.length;
  return `${String(Math.round(barycenter)).padStart(5, '0')}-${name}`;
}

interface ParsedLink {
  from: string;
  to: string;
  relation: string;
}

function parseTopologyLink(raw: string): ParsedLink | null {
  const match = /^(.+?)\s*->\s*(.+?)\s*\((.+)\)$/.exec(raw.trim());
  if (!match) {
    return null;
  }
  return {
    from: match[1].trim(),
    to: match[2].trim(),
    relation: match[3].trim(),
  };
}

function collectEffects(artifact: FlowchartArtifact | null): ParsedEffect[] {
  if (!artifact) {
    return [];
  }
  return artifact.tasks.flatMap((task) =>
    task.transitions.flatMap((transition) =>
      transition.effects
        .map((effect) => parseEffect(effect, task.task_name))
        .filter((item): item is ParsedEffect => Boolean(item))
    )
  );
}

function parseEffect(effect: string, taskName: string): ParsedEffect | null {
  let match = /^acquire (.+) from (.+)$/.exec(effect);
  if (match) {
    return { kind: 'acquire', from: match[2], to: match[1], label: `${match[2]} -> ${match[1]}`, taskName, effect };
  }
  match = /^transfer (.+) -> (.+)$/.exec(effect);
  if (match) {
    return { kind: 'transfer', from: match[1], to: match[2], label: `${match[1]} -> ${match[2]}`, taskName, effect };
  }
  match = /^finish (.+) as (.+)$/.exec(effect);
  if (match) {
    return { kind: 'finish', from: match[1], to: match[2], label: `${match[1]} -> ${match[2]}`, taskName, effect };
  }
  return null;
}

function isForwardMaterialEffect(effect: ParsedEffect): boolean {
  if (effect.kind === 'finish') {
    return false;
  }
  const text = `${effect.from} ${effect.to}`.toLowerCase();
  if (text.includes('reject') || text.includes('drop') || text.includes('scrap')) {
    return false;
  }
  return stageIndex(stageName(effect.to)) >= stageIndex(stageName(effect.from));
}

function collectPipelineSites(effects: ParsedEffect[]): string[] {
  const seen = new Set<string>();
  const sites: string[] = [];
  effects.forEach((effect) => {
    [effect.from, effect.to].forEach((site) => {
      if (seen.has(site)) {
        return;
      }
      seen.add(site);
      sites.push(site);
    });
  });
  return sites.sort((left, right) => stageSortKey(left).localeCompare(stageSortKey(right)));
}

function summarizeArtifact(artifact: FlowchartArtifact | null) {
  const tasks = artifact?.tasks ?? [];
  return {
    taskCount: tasks.length,
    stepCount: tasks.reduce((sum, task) => sum + task.steps.length, 0),
    transitionCount: tasks.reduce((sum, task) => sum + task.transitions.length, 0),
  };
}

function taskRole(name: string): string {
  const lower = name.toLowerCase();
  if (lower.includes('fault') || lower.includes('warning')) return 'fault';
  if (lower.includes('manual') || lower.includes('maintenance') || lower.includes('check')) return 'service';
  if (lower.includes('startup') || lower.includes('init')) return 'startup';
  if (lower.includes('monitor') || lower.includes('supervisor')) return 'monitor';
  return 'process';
}

function taskRoleColor(name: string): string {
  const role = taskRole(name);
  if (role === 'fault') return 'red';
  if (role === 'service') return 'gold';
  if (role === 'startup') return 'cyan';
  if (role === 'monitor') return 'blue';
  return 'green';
}

function effectTagColor(kind: ParsedEffect['kind']): string {
  if (kind === 'acquire') return 'cyan';
  if (kind === 'finish') return 'gold';
  return 'green';
}

function nodeTypeForName(name: string): string {
  const lower = name.toLowerCase();
  if (/^x\d+$/i.test(name)) return 'input_terminal';
  if (/^y\d+$/i.test(name)) return 'output_terminal';
  if (lower.includes('sensor') || lower.includes('wafer_on') || lower.includes('ready')) return 'sensor';
  if (lower.includes('button') || lower.includes('mode_')) return 'switch';
  if (lower.includes('cyl')) return 'cylinder';
  if (lower.includes('axis') || lower.includes('motor')) return 'stepper_pd';
  return 'generic';
}

function portsForNode(nodeType: string): DevicePortMetadata[] {
  if (nodeType === 'input_terminal') return [{ id: 'in', type: 'digital', role: 'consumer' }];
  if (nodeType === 'output_terminal') return [{ id: 'out', type: 'digital', role: 'producer' }];
  return [
    { id: 'in', type: 'generic', role: 'consumer' },
    { id: 'out', type: 'generic', role: 'producer' },
  ];
}

function sourceHandleForNode(name: string): string {
  return /^x\d+$/i.test(name) ? 'in' : 'out';
}

function targetHandleForNode(name: string): string {
  return /^y\d+$/i.test(name) ? 'out' : 'in';
}

function relationColor(relation: string): string {
  const lower = relation.toLowerCase();
  if (lower.includes('electrical')) return '#38bdf8';
  if (lower.includes('pneumatic')) return '#f97316';
  if (lower.includes('logical')) return '#22c55e';
  return '#94a3b8';
}

function stageName(name: string): string {
  const lower = name.toLowerCase();
  if (lower.includes('feed') || lower.includes('cassette')) return 'FEED';
  if (lower.includes('slide')) return 'SLIDE';
  if (lower.includes('arm')) return 'ARM';
  if (lower.includes('orient')) return 'ORIENT';
  if (lower.includes('transfer') || lower.includes('swing') || lower.includes('lift')) return 'TRANSFER';
  if (lower.includes('measure')) return 'MEASURE';
  if (/^[xy]\d+$/i.test(name) || lower.includes('plc') || lower.includes('mode') || lower.includes('button')) return 'IO';
  return 'SYSTEM';
}

function stageIndex(stage: string): number {
  return ['FEED', 'SLIDE', 'ARM', 'ORIENT', 'TRANSFER', 'MEASURE', 'IO', 'SYSTEM'].indexOf(stage);
}

function stageSortKey(name: string): string {
  const stage = stageName(name);
  return `${String(stageIndex(stage)).padStart(2, '0')}-${name}`;
}

function compactSite(name: string): string {
  return name.length > 18 ? `${name.slice(0, 15)}...` : name;
}

function shortSource(source: string): string {
  const normalized = source.replaceAll('\\', '/');
  const segments = normalized.split('/');
  return segments.slice(-2).join('/');
}

function isWorkpieceEndpoint(name: string, artifact: FlowchartArtifact): boolean {
  return artifact.topology.workpiece_sites.some((site) => site.startsWith(`${name}:`)) ||
    artifact.topology.workpiece_holders.some((holder) => holder.startsWith(`${name}:`));
}

const contractPreStyle: React.CSSProperties = {
  maxHeight: 220,
  overflow: 'auto',
  whiteSpace: 'pre-wrap',
  background: '#020617',
  border: '1px solid #1e293b',
  borderRadius: 12,
  padding: 14,
  color: '#e2e8f0',
  lineHeight: 1.55,
};

const editorGridStyle: React.CSSProperties = {
  display: 'grid',
  gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 420px), 1fr))',
  gap: 16,
  alignItems: 'stretch',
};

const editorCanvasShellStyle: React.CSSProperties = {
  position: 'relative',
  minHeight: 380,
  border: '1px solid #1e293b',
  borderRadius: 8,
  background: '#020617',
  overflow: 'hidden',
};

const EDITOR_NODE_WIDTH = 170;

const editorTransitionOverlayStyle: React.CSSProperties = {
  position: 'absolute',
  inset: 0,
  zIndex: 2,
  width: '100%',
  height: '100%',
  pointerEvents: 'auto',
};

const editorTransitionLabelStyle: React.CSSProperties = {
  fill: '#f8fafc',
  fontSize: 11,
  fontWeight: 600,
  paintOrder: 'stroke',
  stroke: '#7c2d12',
  strokeWidth: 4,
  pointerEvents: 'none',
};

const editorNodeCardStyle: React.CSSProperties = {
  width: EDITOR_NODE_WIDTH,
  minHeight: 64,
  display: 'grid',
  gap: 4,
  padding: '10px 12px',
  borderRadius: 8,
  border: '1px solid #475569',
  background: '#0f172a',
  color: '#e2e8f0',
  fontSize: 12,
};

const editorNodeTitleStyle: React.CSSProperties = {
  color: '#f8fafc',
  lineHeight: 1.25,
};

const editorNodeActionStyle: React.CSSProperties = {
  color: '#cbd5e1',
  fontSize: 11,
  lineHeight: 1.3,
};

const editorNodeHandleStyle: React.CSSProperties = {
  width: 8,
  height: 8,
  borderColor: '#bfdbfe',
  background: '#2563eb',
};

const editorResultGridStyle: React.CSSProperties = {
  display: 'grid',
  gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 360px), 1fr))',
  gap: 16,
  marginTop: 16,
};

const guardRowsStyle: React.CSSProperties = {
  display: 'grid',
  gap: 8,
  minWidth: 0,
};

const stepActionRowStyle: React.CSSProperties = {
  display: 'flex',
  flexWrap: 'wrap',
  gap: 8,
  alignItems: 'center',
  minWidth: 0,
};

const guardRowStyle: React.CSSProperties = {
  display: 'flex',
  flexWrap: 'wrap',
  gap: 8,
  alignItems: 'center',
  minWidth: 0,
  padding: 8,
  border: '1px solid #1e293b',
  borderRadius: 6,
  background: '#0f172a',
};

const fieldLabelStyle: React.CSSProperties = {
  fontSize: 12,
  fontWeight: 600,
  color: '#475569',
};

const sfcStripStyle: React.CSSProperties = {
  display: 'flex',
  gap: 8,
  overflowX: 'auto',
  padding: '10px 2px',
};

const sfcStepStyle: React.CSSProperties = {
  minWidth: 150,
  maxWidth: 180,
  display: 'grid',
  gap: 4,
  border: '1px solid #334155',
  background: '#111827',
  borderRadius: 6,
  padding: '9px 10px',
};

const sfcTransitionStyle: React.CSSProperties = {
  alignSelf: 'center',
  minWidth: 28,
  height: 2,
  background: '#64748b',
  color: '#94a3b8',
  fontSize: 10,
  textAlign: 'center',
};

export default FlowchartReviewPage;
