#![forbid(unsafe_code)]

use runtime_core::{
    Action, AxisFaultRouteKind, AxisFaultRouteRule, AxisFaultRouting, AxisMoveKind, CamAnalogField,
    CamDigitalField, CompareOp, ExprOp, ExprProgram, Instr, Program, StepId, Timeout,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CodegenError {
    ProgramHasNoTasks,
    StepIdOutOfRange,
}

/// Generates a Rust source module that defines a `'static` `runtime_core::Program`.
///
/// Notes:
/// - This is intentionally simple and "stringly typed"; it is an internal build artifact generator.
/// - The generated module contains no heap allocation and uses only `static` arrays.
pub fn generate_program_module(
    program: &Program<'_>,
    module_name: &str,
) -> Result<String, CodegenError> {
    if program.tasks.is_empty() {
        return Err(CodegenError::ProgramHasNoTasks);
    }

    // Basic sanity: StepIds should fit the arrays they index.
    for (tidx, task) in program.tasks.iter().enumerate() {
        if task.entry.0 as usize >= task.steps.len() {
            return Err(CodegenError::StepIdOutOfRange);
        }
        for (sidx, step) in task.steps.iter().enumerate() {
            // Ensure any referenced StepId is in-range.
            fn check(id: StepId, len: usize) -> bool {
                (id.0 as usize) < len
            }
            match step.instr {
                Instr::Action { next, .. } => {
                    if !check(next, task.steps.len()) {
                        return Err(CodegenError::StepIdOutOfRange);
                    }
                }
                Instr::WaitDigital { next, timeout, .. } => {
                    if !check(next, task.steps.len()) {
                        return Err(CodegenError::StepIdOutOfRange);
                    }
                    if let Some(tmo) = timeout {
                        if !check(tmo.target, task.steps.len()) {
                            return Err(CodegenError::StepIdOutOfRange);
                        }
                    }
                }
                Instr::WaitAnalog { next, timeout, .. } => {
                    if !check(next, task.steps.len()) {
                        return Err(CodegenError::StepIdOutOfRange);
                    }
                    if let Some(tmo) = timeout {
                        if !check(tmo.target, task.steps.len()) {
                            return Err(CodegenError::StepIdOutOfRange);
                        }
                    }
                }
                Instr::WaitExpr { next, timeout, .. } => {
                    if !check(next, task.steps.len()) {
                        return Err(CodegenError::StepIdOutOfRange);
                    }
                    if let Some(tmo) = timeout
                        && !check(tmo.target, task.steps.len())
                    {
                        return Err(CodegenError::StepIdOutOfRange);
                    }
                }
                Instr::WaitCamDigital { next, timeout, .. } => {
                    if !check(next, task.steps.len()) {
                        return Err(CodegenError::StepIdOutOfRange);
                    }
                    if let Some(tmo) = timeout
                        && !check(tmo.target, task.steps.len())
                    {
                        return Err(CodegenError::StepIdOutOfRange);
                    }
                }
                Instr::WaitCamAnalog { next, timeout, .. } => {
                    if !check(next, task.steps.len()) {
                        return Err(CodegenError::StepIdOutOfRange);
                    }
                    if let Some(tmo) = timeout
                        && !check(tmo.target, task.steps.len())
                    {
                        return Err(CodegenError::StepIdOutOfRange);
                    }
                }
                Instr::Delay { next, .. } => {
                    if !check(next, task.steps.len()) {
                        return Err(CodegenError::StepIdOutOfRange);
                    }
                }
                Instr::Goto { target } => {
                    if !check(target, task.steps.len()) {
                        return Err(CodegenError::StepIdOutOfRange);
                    }
                }
                Instr::Halt => {}
            }

            // Also ensure StepId equals its index range expectations are stable, nothing else.
            let _ = (tidx, sidx);
        }
    }

    let mut out = String::new();
    out.push_str("// @generated by crates/codegen\n");
    out.push_str("#[allow(clippy::all)]\n");
    out.push_str("#[allow(non_upper_case_globals)]\n");
    out.push_str("#[allow(non_snake_case)]\n");
    out.push_str("#[allow(non_camel_case_types)]\n");
    out.push_str(&format!("pub mod {module_name} {{\n"));
    out.push_str(
        "  use io_traits::{AnalogInputId, DigitalInputId, DigitalOutputId, AnalogOutputId};\n",
    );
    out.push_str("  use runtime_core::{Action, AnalogRange, AntiWindup, AxisFaultRouteKind, AxisFaultRouteRule, AxisFaultRouting, AxisMotionCommand, AxisMoveKind, CamAnalogField, CamDigitalField, CompareOp, ExprOp, ExprProgram, Instr, PidConfig, Program, Step, StepId, Task, Timeout};\n\n");

    // Emit actions arrays, then steps, then tasks, then program.
    for (tidx, task) in program.tasks.iter().enumerate() {
        for (sidx, step) in task.steps.iter().enumerate() {
            if let Instr::Action { actions, .. } = step.instr {
                out.push_str(&format!(
                    "  static T{tidx}_S{sidx}_ACTIONS: [Action; {}] = [\n",
                    actions.len()
                ));
                for a in actions {
                    out.push_str("    ");
                    out.push_str(&format_action(a));
                    out.push_str(",\n");
                }
                out.push_str("  ];\n\n");
            }
            if let Instr::WaitAnalog { ranges, .. } = step.instr {
                out.push_str(&format!(
                    "  static T{tidx}_S{sidx}_RANGES: [AnalogRange; {}] = [\n",
                    ranges.len()
                ));
                for r in ranges {
                    out.push_str(&format!(
                        "    AnalogRange {{ min: {}, max: {} }},\n",
                        format_f32(r.min),
                        format_f32(r.max)
                    ));
                }
                out.push_str("  ];\n\n");
            }
        }

        out.push_str(&format!(
            "  static T{tidx}_STEPS: [Step<'static>; {}] = [\n",
            task.steps.len()
        ));
        for (sidx, step) in task.steps.iter().enumerate() {
            out.push_str("    Step { name: ");
            out.push_str(&format!("{:?}", step.name));
            out.push_str(", instr: ");
            out.push_str(&format_instr(tidx, sidx, &step.instr));
            out.push_str(" },\n");
        }
        out.push_str("  ];\n\n");
    }

    out.push_str(&format!(
        "  static TASKS: [Task<'static>; {}] = [\n",
        program.tasks.len()
    ));
    for (tidx, task) in program.tasks.iter().enumerate() {
        out.push_str("    Task { name: ");
        out.push_str(&format!("{:?}", task.name));
        out.push_str(&format!(
            ", steps: &T{tidx}_STEPS, entry: StepId({}) }},\n",
            task.entry.0
        ));
    }
    out.push_str("  ];\n\n");

    if program.pid_loops.is_empty() {
        out.push_str(
            "  pub static PROGRAM: Program<'static> = Program { tasks: &TASKS, pid_loops: &[], var_init: &[], cam_configs: &[], cam_tables: &[], axis_fault_policies: &[] };\n",
        );
    } else {
        out.push_str(&format!(
            "  static PID_LOOPS: [PidConfig; {}] = [\n",
            program.pid_loops.len()
        ));
        for cfg in program.pid_loops {
            out.push_str("    ");
            out.push_str(&format_pid_config(cfg));
            out.push_str(",\n");
        }
        out.push_str("  ];\n\n");
        out.push_str("  pub static PROGRAM: Program<'static> = Program { tasks: &TASKS, pid_loops: &PID_LOOPS, var_init: &[], cam_configs: &[], cam_tables: &[], axis_fault_policies: &[] };\n");
    }
    out.push_str("}\n");

    Ok(out)
}

fn format_action(a: &Action) -> String {
    match *a {
        Action::SetDigital { id, value } => format!(
            "Action::SetDigital {{ id: DigitalOutputId({}), value: {} }}",
            id.0, value
        ),
        Action::SetAnalog { id, value } => format!(
            "Action::SetAnalog {{ id: AnalogOutputId({}), value: {} }}",
            id.0,
            format_f32(value)
        ),
        Action::SetAnalogExpr { id, expr } => format!(
            "Action::SetAnalogExpr {{ id: AnalogOutputId({}), expr: {} }}",
            id.0,
            format_expr_program(&expr)
        ),
        Action::Compute { target_var, expr } => format!(
            "Action::Compute {{ target_var: {}, expr: {} }}",
            target_var,
            format_expr_program(&expr)
        ),
        Action::CallExtern {
            function,
            arg_exprs,
            binding_vars,
        } => format!(
            "Action::CallExtern {{ function: {:?}, arg_exprs: &{}, binding_vars: &{} }}",
            function,
            format_expr_program_slice(arg_exprs),
            format_u16_slice(binding_vars)
        ),
        Action::CamEngage { cam_index } => {
            format!("Action::CamEngage {{ cam_index: {cam_index} }}")
        }
        Action::CamDisengage { cam_index } => {
            format!("Action::CamDisengage {{ cam_index: {cam_index} }}")
        }
        Action::CamSwitch {
            cam_index,
            table_index,
        } => format!(
            "Action::CamSwitch {{ cam_index: {}, table_index: {} }}",
            cam_index, table_index
        ),
        Action::CamPhase {
            cam_index,
            offset_expr,
        } => format!(
            "Action::CamPhase {{ cam_index: {}, offset_expr: {} }}",
            cam_index,
            format_expr_program(&offset_expr)
        ),
        Action::AxisMove { command } => format!(
            "Action::AxisMove {{ command: AxisMotionCommand {{ target: {:?}, port: {:?}, kind: AxisMoveKind::{}, value: {}, speed: {}, require_homed: {}, timeout: {}, fault_routing: {} }} }}",
            command.target,
            command.port,
            match command.kind {
                AxisMoveKind::Relative => "Relative",
                AxisMoveKind::Absolute => "Absolute",
            },
            format_f32(command.value),
            format_f32(command.speed),
            command.require_homed,
            format_axis_timeout(command.timeout),
            format_axis_fault_routing(command.fault_routing),
        ),
        Action::Extend { output } => {
            format!("Action::Extend {{ output: DigitalOutputId({}) }}", output.0)
        }
        Action::Retract { output } => format!(
            "Action::Retract {{ output: DigitalOutputId({}) }}",
            output.0
        ),
        Action::Log {
            message_id,
            message,
        } => format!(
            "Action::Log {{ message_id: {}, message: {:?} }}",
            message_id, message
        ),
    }
}

fn format_expr_program(expr: &ExprProgram) -> String {
    let mut ops = String::new();
    for (idx, op) in expr.ops.iter().enumerate() {
        if idx > 0 {
            ops.push_str(", ");
        }
        ops.push_str(&format_expr_op(op));
    }
    format!("ExprProgram {{ ops: [{ops}], len: {} }}", expr.len)
}

fn format_expr_program_slice(exprs: &[ExprProgram]) -> String {
    let mut out = String::new();
    out.push('[');
    for (idx, expr) in exprs.iter().enumerate() {
        if idx > 0 {
            out.push_str(", ");
        }
        out.push_str(&format_expr_program(expr));
    }
    out.push(']');
    out
}

fn format_u16_slice(values: &[u16]) -> String {
    let mut out = String::new();
    out.push('[');
    for (idx, value) in values.iter().enumerate() {
        if idx > 0 {
            out.push_str(", ");
        }
        out.push_str(&value.to_string());
    }
    out.push(']');
    out
}

fn format_axis_timeout(timeout: Option<Timeout>) -> String {
    match timeout {
        Some(timeout) => format!(
            "Some(Timeout {{ after_ticks: {}, target: StepId({}) }})",
            timeout.after_ticks, timeout.target.0
        ),
        None => "None".to_string(),
    }
}

fn format_axis_fault_route_kind(kind: AxisFaultRouteKind) -> &'static str {
    match kind {
        AxisFaultRouteKind::Reject => "Reject",
        AxisFaultRouteKind::Motion => "Motion",
        AxisFaultRouteKind::Safety => "Safety",
        AxisFaultRouteKind::Vendor => "Vendor",
    }
}

fn format_axis_fault_route_rules(routes: &[AxisFaultRouteRule]) -> String {
    let mut out = String::new();
    out.push('[');
    for (idx, route) in routes.iter().enumerate() {
        if idx > 0 {
            out.push_str(", ");
        }
        let kind = match route.kind {
            Some(kind) => format!(
                "Some(AxisFaultRouteKind::{})",
                format_axis_fault_route_kind(kind)
            ),
            None => "None".to_string(),
        };
        let code = match route.code {
            Some(code) => format!("Some({code})"),
            None => "None".to_string(),
        };
        out.push_str(&format!(
            "AxisFaultRouteRule {{ kind: {kind}, code: {code}, target: StepId({}) }}",
            route.target.0
        ));
    }
    out.push(']');
    out
}

fn format_axis_fault_routing(routing: Option<AxisFaultRouting>) -> String {
    match routing {
        Some(routing) => format!(
            "Some(AxisFaultRouting {{ on_reject: StepId({}), on_motion_fault: StepId({}), on_safety_fault: StepId({}), on_reject_routes: &{}, on_motion_fault_routes: &{}, on_safety_fault_routes: &{} }})",
            routing.on_reject.0,
            routing.on_motion_fault.0,
            routing.on_safety_fault.0,
            format_axis_fault_route_rules(routing.on_reject_routes),
            format_axis_fault_route_rules(routing.on_motion_fault_routes),
            format_axis_fault_route_rules(routing.on_safety_fault_routes),
        ),
        None => "None".to_string(),
    }
}

fn format_expr_op(op: &ExprOp) -> String {
    match *op {
        ExprOp::PushLiteral(v) => format!("ExprOp::PushLiteral({})", format_f32(v)),
        ExprOp::PushVariable(idx) => format!("ExprOp::PushVariable({idx})"),
        ExprOp::Add => "ExprOp::Add".to_string(),
        ExprOp::Sub => "ExprOp::Sub".to_string(),
        ExprOp::Mul => "ExprOp::Mul".to_string(),
        ExprOp::Div => "ExprOp::Div".to_string(),
        ExprOp::Mod => "ExprOp::Mod".to_string(),
        ExprOp::Neg => "ExprOp::Neg".to_string(),
        ExprOp::CallAbs => "ExprOp::CallAbs".to_string(),
        ExprOp::CallMin => "ExprOp::CallMin".to_string(),
        ExprOp::CallMax => "ExprOp::CallMax".to_string(),
        ExprOp::CallSin => "ExprOp::CallSin".to_string(),
        ExprOp::CallCos => "ExprOp::CallCos".to_string(),
        ExprOp::CallSqrt => "ExprOp::CallSqrt".to_string(),
        ExprOp::CallPow => "ExprOp::CallPow".to_string(),
        ExprOp::CallFmod => "ExprOp::CallFmod".to_string(),
        ExprOp::CallClamp => "ExprOp::CallClamp".to_string(),
        ExprOp::CmpEq => "ExprOp::CmpEq".to_string(),
        ExprOp::CmpNe => "ExprOp::CmpNe".to_string(),
        ExprOp::CmpGt => "ExprOp::CmpGt".to_string(),
        ExprOp::CmpLt => "ExprOp::CmpLt".to_string(),
        ExprOp::CmpGe => "ExprOp::CmpGe".to_string(),
        ExprOp::CmpLe => "ExprOp::CmpLe".to_string(),
        ExprOp::BoolAnd => "ExprOp::BoolAnd".to_string(),
        ExprOp::BoolOr => "ExprOp::BoolOr".to_string(),
        ExprOp::BoolNot => "ExprOp::BoolNot".to_string(),
    }
}

fn format_instr(tidx: usize, sidx: usize, instr: &Instr<'_>) -> String {
    match *instr {
        Instr::Action { actions, next } => {
            // Reuse the per-step actions array if it exists, otherwise emit an empty slice.
            if actions.is_empty() {
                format!("Instr::Action {{ actions: &[], next: StepId({}) }}", next.0)
            } else {
                format!(
                    "Instr::Action {{ actions: &T{}_S{}_ACTIONS, next: StepId({}) }}",
                    tidx, sidx, next.0
                )
            }
        }
        Instr::WaitDigital {
            id,
            equals,
            next,
            timeout,
        } => {
            let tmo = match timeout {
                None => "None".to_string(),
                Some(Timeout {
                    after_ticks,
                    target,
                }) => format!(
                    "Some(Timeout {{ after_ticks: {}, target: StepId({}) }})",
                    after_ticks, target.0
                ),
            };
            format!(
                "Instr::WaitDigital {{ id: DigitalInputId({}), equals: {}, next: StepId({}), timeout: {} }}",
                id.0, equals, next.0, tmo
            )
        }
        Instr::WaitAnalog {
            id,
            ranges,
            next,
            timeout,
        } => {
            let tmo = match timeout {
                None => "None".to_string(),
                Some(Timeout {
                    after_ticks,
                    target,
                }) => format!(
                    "Some(Timeout {{ after_ticks: {}, target: StepId({}) }})",
                    after_ticks, target.0
                ),
            };
            let ranges_ref = if ranges.is_empty() {
                "&[]".to_string()
            } else {
                format!("&T{}_S{}_RANGES", tidx, sidx)
            };
            format!(
                "Instr::WaitAnalog {{ id: AnalogInputId({}), ranges: {}, next: StepId({}), timeout: {} }}",
                id.0, ranges_ref, next.0, tmo
            )
        }
        Instr::WaitExpr {
            left,
            op,
            right,
            next,
            timeout,
        } => {
            let tmo = match timeout {
                None => "None".to_string(),
                Some(Timeout {
                    after_ticks,
                    target,
                }) => format!(
                    "Some(Timeout {{ after_ticks: {}, target: StepId({}) }})",
                    after_ticks, target.0
                ),
            };
            format!(
                "Instr::WaitExpr {{ left: {}, op: {}, right: {}, next: StepId({}), timeout: {} }}",
                format_expr_program(&left),
                format_compare_op(op),
                format_expr_program(&right),
                next.0,
                tmo
            )
        }
        Instr::WaitCamDigital {
            cam_index,
            field,
            equals,
            next,
            timeout,
        } => {
            let tmo = match timeout {
                None => "None".to_string(),
                Some(Timeout {
                    after_ticks,
                    target,
                }) => format!(
                    "Some(Timeout {{ after_ticks: {}, target: StepId({}) }})",
                    after_ticks, target.0
                ),
            };
            format!(
                "Instr::WaitCamDigital {{ cam_index: {}, field: {}, equals: {}, next: StepId({}), timeout: {} }}",
                cam_index,
                format_cam_digital_field(field),
                equals,
                next.0,
                tmo
            )
        }
        Instr::WaitCamAnalog {
            cam_index,
            field,
            op,
            value,
            next,
            timeout,
        } => {
            let tmo = match timeout {
                None => "None".to_string(),
                Some(Timeout {
                    after_ticks,
                    target,
                }) => format!(
                    "Some(Timeout {{ after_ticks: {}, target: StepId({}) }})",
                    after_ticks, target.0
                ),
            };
            format!(
                "Instr::WaitCamAnalog {{ cam_index: {}, field: {}, op: {}, value: {}, next: StepId({}), timeout: {} }}",
                cam_index,
                format_cam_analog_field(field),
                format_compare_op(op),
                format_f32(value),
                next.0,
                tmo
            )
        }
        Instr::Delay { ticks, next } => format!(
            "Instr::Delay {{ ticks: {}, next: StepId({}) }}",
            ticks, next.0
        ),
        Instr::Goto { target } => format!("Instr::Goto {{ target: StepId({}) }}", target.0),
        Instr::Halt => "Instr::Halt".to_string(),
    }
}

fn format_compare_op(op: CompareOp) -> &'static str {
    match op {
        CompareOp::Eq => "CompareOp::Eq",
        CompareOp::Ne => "CompareOp::Ne",
        CompareOp::Gt => "CompareOp::Gt",
        CompareOp::Lt => "CompareOp::Lt",
        CompareOp::Ge => "CompareOp::Ge",
        CompareOp::Le => "CompareOp::Le",
    }
}

fn format_cam_digital_field(field: CamDigitalField) -> &'static str {
    match field {
        CamDigitalField::Engage => "CamDigitalField::Engage",
        CamDigitalField::InSync => "CamDigitalField::InSync",
        CamDigitalField::Fault => "CamDigitalField::Fault",
    }
}

fn format_cam_analog_field(field: CamAnalogField) -> &'static str {
    match field {
        CamAnalogField::FollowingError => "CamAnalogField::FollowingError",
        CamAnalogField::MasterPos => "CamAnalogField::MasterPos",
        CamAnalogField::SlaveCmd => "CamAnalogField::SlaveCmd",
    }
}

fn format_f32(v: f32) -> String {
    if v.is_finite() {
        // Ensure `1.0` stays `1.0` (not `1`) to avoid type inference surprises in generated code.
        let s = format!("{v}");
        if s.contains('.') || s.contains('e') || s.contains('E') {
            s
        } else {
            format!("{s}.0")
        }
    } else if v.is_nan() {
        "f32::NAN".to_string()
    } else if v.is_sign_negative() {
        "f32::NEG_INFINITY".to_string()
    } else {
        "f32::INFINITY".to_string()
    }
}

fn format_pid_config(cfg: &runtime_core::PidConfig) -> String {
    let aw = match cfg.anti_windup {
        runtime_core::AntiWindup::ConditionalIntegration => "AntiWindup::ConditionalIntegration",
    };

    format!(
        "PidConfig {{ pv: AnalogInputId({}), out: AnalogOutputId({}), sp: {}, kp: {}, ki: {}, kd: {}, dt_s: {}, period_ticks: {}, limit_min: {}, limit_max: {}, anti_windup: {} }}",
        cfg.pv.0,
        cfg.out.0,
        format_f32(cfg.sp),
        format_f32(cfg.kp),
        format_f32(cfg.ki),
        format_f32(cfg.kd),
        format_f32(cfg.dt_s),
        cfg.period_ticks,
        format_f32(cfg.limit_min),
        format_f32(cfg.limit_max),
        aw
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use io_traits::{DigitalInputId, DigitalOutputId};
    use runtime_core::{Instr, Step, Task};

    #[test]
    fn generated_module_parses_with_syn() {
        static ACTIONS: [Action; 1] = [Action::SetDigital {
            id: DigitalOutputId(0),
            value: true,
        }];
        static STEPS: [Step<'static>; 2] = [
            Step {
                name: "set",
                instr: Instr::Action {
                    actions: &ACTIONS,
                    next: StepId(1),
                },
            },
            Step {
                name: "wait",
                instr: Instr::WaitDigital {
                    id: DigitalInputId(0),
                    equals: true,
                    next: StepId(1),
                    timeout: Some(Timeout {
                        after_ticks: 3,
                        target: StepId(0),
                    }),
                },
            },
        ];
        static TASKS: [Task<'static>; 1] = [Task {
            name: "main",
            steps: &STEPS,
            entry: StepId(0),
        }];
        static PROGRAM: Program<'static> = Program {
            tasks: &TASKS,
            pid_loops: &[],
            var_init: &[],
            cam_configs: &[],
            cam_tables: &[],
            axis_fault_policies: &[],
        };

        let src = generate_program_module(&PROGRAM, "gen").expect("codegen ok");
        // Parse the generated source. We treat it as a standalone item file.
        syn::parse_file(&src).expect("generated Rust should parse");
        assert!(src.contains("pub static PROGRAM: Program<'static>"));
    }
}
