#![forbid(unsafe_code)]

use runtime_core::{Action, Instr, Program, StepId, Timeout};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CodegenError {
    ProgramHasNoTasks,
    StepIdOutOfRange,
}

/// Generates a Rust source module that defines a `'static` `runtime_core::Program`.
///
/// Notes:
/// - This is intentionally simple and "stringly typed"; it is an internal build artifact generator.
/// - The generated module contains no heap allocation and uses only `static` arrays.
pub fn generate_program_module(program: &Program<'_>, module_name: &str) -> Result<String, CodegenError> {
    if program.tasks.is_empty() {
        return Err(CodegenError::ProgramHasNoTasks);
    }

    // Basic sanity: StepIds should fit the arrays they index.
    for (tidx, task) in program.tasks.iter().enumerate() {
        if task.entry.0 as usize >= task.steps.len() {
            return Err(CodegenError::StepIdOutOfRange);
        }
        for (sidx, step) in task.steps.iter().enumerate() {
            // Ensure any referenced StepId is in-range.
            fn check(id: StepId, len: usize) -> bool {
                (id.0 as usize) < len
            }
            match step.instr {
                Instr::Action { next, .. } => {
                    if !check(next, task.steps.len()) { return Err(CodegenError::StepIdOutOfRange); }
                }
                Instr::WaitDigital { next, timeout, .. } => {
                    if !check(next, task.steps.len()) { return Err(CodegenError::StepIdOutOfRange); }
                    if let Some(tmo) = timeout {
                        if !check(tmo.target, task.steps.len()) { return Err(CodegenError::StepIdOutOfRange); }
                    }
                }
                Instr::Delay { next, .. } => {
                    if !check(next, task.steps.len()) { return Err(CodegenError::StepIdOutOfRange); }
                }
                Instr::Goto { target } => {
                    if !check(target, task.steps.len()) { return Err(CodegenError::StepIdOutOfRange); }
                }
                Instr::Halt => {}
            }

            // Also ensure StepId equals its index range expectations are stable, nothing else.
            let _ = (tidx, sidx);
        }
    }

    let mut out = String::new();
    out.push_str("// @generated by crates/codegen\n");
    out.push_str("#[allow(clippy::all)]\n");
    out.push_str("#[allow(non_upper_case_globals)]\n");
    out.push_str("#[allow(non_snake_case)]\n");
    out.push_str("#[allow(non_camel_case_types)]\n");
    out.push_str(&format!("pub mod {module_name} {{\n"));
    out.push_str("  use io_traits::{DigitalInputId, DigitalOutputId, AnalogOutputId};\n");
    out.push_str("  use runtime_core::{Action, Instr, Program, Step, StepId, Task, Timeout};\n\n");

    // Emit actions arrays, then steps, then tasks, then program.
    for (tidx, task) in program.tasks.iter().enumerate() {
        for (sidx, step) in task.steps.iter().enumerate() {
            if let Instr::Action { actions, .. } = step.instr {
                out.push_str(&format!("  static T{tidx}_S{sidx}_ACTIONS: [Action; {}] = [\n", actions.len()));
                for a in actions {
                    out.push_str("    ");
                    out.push_str(&format_action(a));
                    out.push_str(",\n");
                }
                out.push_str("  ];\n\n");
            }
        }

        out.push_str(&format!("  static T{tidx}_STEPS: [Step<'static>; {}] = [\n", task.steps.len()));
        for (sidx, step) in task.steps.iter().enumerate() {
            out.push_str("    Step { name: ");
            out.push_str(&format!("{:?}", step.name));
            out.push_str(", instr: ");
            out.push_str(&format_instr(tidx, sidx, &step.instr));
            out.push_str(" },\n");
        }
        out.push_str("  ];\n\n");
    }

    out.push_str(&format!("  static TASKS: [Task<'static>; {}] = [\n", program.tasks.len()));
    for (tidx, task) in program.tasks.iter().enumerate() {
        out.push_str("    Task { name: ");
        out.push_str(&format!("{:?}", task.name));
        out.push_str(&format!(", steps: &T{tidx}_STEPS, entry: StepId({}) }},\n", task.entry.0));
    }
    out.push_str("  ];\n\n");
    out.push_str("  pub static PROGRAM: Program<'static> = Program { tasks: &TASKS };\n");
    out.push_str("}\n");

    Ok(out)
}

fn format_action(a: &Action) -> String {
    match *a {
        Action::SetDigital { id, value } => format!(
            "Action::SetDigital {{ id: DigitalOutputId({}), value: {} }}",
            id.0, value
        ),
        Action::SetAnalog { id, value } => format!(
            "Action::SetAnalog {{ id: AnalogOutputId({}), value: {} }}",
            id.0, format_f32(value)
        ),
        Action::Extend { output } => format!(
            "Action::Extend {{ output: DigitalOutputId({}) }}",
            output.0
        ),
        Action::Retract { output } => format!(
            "Action::Retract {{ output: DigitalOutputId({}) }}",
            output.0
        ),
        Action::Log {
            message_id,
            message,
        } => format!(
            "Action::Log {{ message_id: {}, message: {:?} }}",
            message_id, message
        ),
    }
}

fn format_instr(tidx: usize, sidx: usize, instr: &Instr<'_>) -> String {
    match *instr {
        Instr::Action { actions, next } => {
            // Reuse the per-step actions array if it exists, otherwise emit an empty slice.
            if actions.is_empty() {
                format!("Instr::Action {{ actions: &[], next: StepId({}) }}", next.0)
            } else {
                format!(
                    "Instr::Action {{ actions: &T{}_S{}_ACTIONS, next: StepId({}) }}",
                    tidx, sidx, next.0
                )
            }
        }
        Instr::WaitDigital {
            id,
            equals,
            next,
            timeout,
        } => {
            let tmo = match timeout {
                None => "None".to_string(),
                Some(Timeout { after_ticks, target }) => format!(
                    "Some(Timeout {{ after_ticks: {}, target: StepId({}) }})",
                    after_ticks, target.0
                ),
            };
            format!(
                "Instr::WaitDigital {{ id: DigitalInputId({}), equals: {}, next: StepId({}), timeout: {} }}",
                id.0, equals, next.0, tmo
            )
        }
        Instr::Delay { ticks, next } => format!(
            "Instr::Delay {{ ticks: {}, next: StepId({}) }}",
            ticks, next.0
        ),
        Instr::Goto { target } => format!("Instr::Goto {{ target: StepId({}) }}", target.0),
        Instr::Halt => "Instr::Halt".to_string(),
    }
}

fn format_f32(v: f32) -> String {
    if v.is_finite() {
        // Ensure `1.0` stays `1.0` (not `1`) to avoid type inference surprises in generated code.
        let s = format!("{v}");
        if s.contains('.') || s.contains('e') || s.contains('E') {
            s
        } else {
            format!("{s}.0")
        }
    } else if v.is_nan() {
        "f32::NAN".to_string()
    } else if v.is_sign_negative() {
        "f32::NEG_INFINITY".to_string()
    } else {
        "f32::INFINITY".to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use io_traits::{DigitalInputId, DigitalOutputId};
    use runtime_core::{Instr, Step, Task};

    #[test]
    fn generated_module_parses_with_syn() {
        static ACTIONS: [Action; 1] = [Action::SetDigital {
            id: DigitalOutputId(0),
            value: true,
        }];
        static STEPS: [Step<'static>; 2] = [
            Step {
                name: "set",
                instr: Instr::Action {
                    actions: &ACTIONS,
                    next: StepId(1),
                },
            },
            Step {
                name: "wait",
                instr: Instr::WaitDigital {
                    id: DigitalInputId(0),
                    equals: true,
                    next: StepId(1),
                    timeout: Some(Timeout {
                        after_ticks: 3,
                        target: StepId(0),
                    }),
                },
            },
        ];
        static TASKS: [Task<'static>; 1] = [Task {
            name: "main",
            steps: &STEPS,
            entry: StepId(0),
        }];
        static PROGRAM: Program<'static> = Program { tasks: &TASKS };

        let src = generate_program_module(&PROGRAM, "gen").expect("codegen ok");
        // Parse the generated source. We treat it as a standalone item file.
        syn::parse_file(&src).expect("generated Rust should parse");
        assert!(src.contains("pub static PROGRAM: Program<'static>"));
    }
}
