use std::{collections::BTreeMap, env, fs, path::PathBuf};

fn main() {
    // Make `memory.x` visible to the linker when building for embedded targets.
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR must be set"));
    fs::write(out_dir.join("memory.x"), include_bytes!("memory.x")).expect("write memory.x");
    println!("cargo:rustc-link-search={}", out_dir.display());
    println!("cargo:rerun-if-changed=memory.x");

    // Allow injecting a generated Program module at build time.
    //
    // If `RUST_PLC_GENERATED_PROGRAM_RS` is set to a path, we copy it into OUT_DIR and include it.
    // Otherwise we emit a tiny default program that just halts.
    let generated_path = out_dir.join("generated_program.rs");
    println!("cargo:rerun-if-env-changed=RUST_PLC_GENERATED_PROGRAM_RS");
    match env::var("RUST_PLC_GENERATED_PROGRAM_RS") {
        Ok(path) => {
            let contents = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("failed to read RUST_PLC_GENERATED_PROGRAM_RS={path}: {e}"));
            fs::write(&generated_path, contents).expect("write generated_program.rs");
        }
        Err(_) => {
            fs::write(&generated_path, default_generated_program()).expect("write default generated_program.rs");
        }
    }

    // Compile-time embed of IO map TOML (optional).
    let io_map_rs_path = out_dir.join("io_map.rs");
    println!("cargo:rerun-if-env-changed=RUST_PLC_IO_MAP_TOML");
    match env::var("RUST_PLC_IO_MAP_TOML") {
        Ok(path) => {
            let toml_str = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("failed to read RUST_PLC_IO_MAP_TOML={path}: {e}"));
            let map = parse_io_map(&toml_str).unwrap_or_else(|e| panic!("invalid io map TOML: {e}"));
            fs::write(&io_map_rs_path, render_io_map_rs(&map)).expect("write io_map.rs");
        }
        Err(_) => {
            fs::write(&io_map_rs_path, render_io_map_rs(&IoMap::default())).expect("write io_map.rs");
        }
    }
}

#[derive(Debug, Default)]
struct IoMap {
    digital_inputs: BTreeMap<u16, u8>,
    digital_outputs: BTreeMap<u16, u8>,
}

fn parse_io_map(input: &str) -> Result<IoMap, String> {
    let v: toml::Value = toml::from_str(input).map_err(|e| e.to_string())?;
    let di = v
        .get("digital_inputs")
        .and_then(|v| v.as_table())
        .ok_or_else(|| "missing [digital_inputs]".to_string())?;
    let do_ = v
        .get("digital_outputs")
        .and_then(|v| v.as_table())
        .ok_or_else(|| "missing [digital_outputs]".to_string())?;

    Ok(IoMap {
        digital_inputs: parse_section(di, "di")?,
        digital_outputs: parse_section(do_, "do")?,
    })
}

fn parse_section(t: &toml::value::Table, prefix: &str) -> Result<BTreeMap<u16, u8>, String> {
    let mut out = BTreeMap::<u16, u8>::new();
    for (k, v) in t {
        let id_str = k
            .strip_prefix(prefix)
            .ok_or_else(|| format!("invalid key {k:?} (expected {prefix}<id>)"))?;
        let id: u16 = id_str
            .parse()
            .map_err(|_| format!("invalid key {k:?} (expected {prefix}<id>)"))?;
        let gpio = v
            .as_integer()
            .ok_or_else(|| format!("invalid value for {k:?} (expected integer gpio)"))?;
        if !(0..=29).contains(&gpio) {
            return Err(format!(
                "invalid gpio {gpio} for {prefix}{id} (allowed: 0..=29)"
            ));
        }
        out.insert(id, gpio as u8);
    }
    Ok(out)
}

fn render_io_map_rs(map: &IoMap) -> String {
    const MAX_DI: usize = 32;
    const MAX_DO: usize = 32;
    const UNUSED: u8 = 255;

    let mut di = [UNUSED; MAX_DI];
    let mut do_ = [UNUSED; MAX_DO];

    for (&id, &gpio) in &map.digital_inputs {
        let idx = id as usize;
        if idx >= MAX_DI {
            panic!("di{id} exceeds MAX_DI={MAX_DI}");
        }
        di[idx] = gpio;
    }
    for (&id, &gpio) in &map.digital_outputs {
        let idx = id as usize;
        if idx >= MAX_DO {
            panic!("do{id} exceeds MAX_DO={MAX_DO}");
        }
        do_[idx] = gpio;
    }

    let mut out = String::new();
    out.push_str("// @generated by board-rp2040 build.rs\n");
    out.push_str("pub const UNUSED_GPIO: u8 = 255;\n");
    out.push_str(&format!("pub const MAX_DI: usize = {MAX_DI};\n"));
    out.push_str(&format!("pub const MAX_DO: usize = {MAX_DO};\n"));
    out.push_str("pub const DI_GPIO: [u8; MAX_DI] = [\n");
    for v in di {
        out.push_str(&format!("  {v},\n"));
    }
    out.push_str("];\n");
    out.push_str("pub const DO_GPIO: [u8; MAX_DO] = [\n");
    for v in do_ {
        out.push_str(&format!("  {v},\n"));
    }
    out.push_str("];\n");
    out
}

fn default_generated_program() -> &'static str {
    r#"// @generated default board-rp2040 program (no external generated Program provided)
#[allow(clippy::all)]

pub mod generated {
  use runtime_core::{Instr, Program, Step, StepId, Task};

  static STEPS: [Step<'static>; 1] = [
    Step { name: "halt", instr: Instr::Halt },
  ];

  static TASKS: [Task<'static>; 1] = [
    Task { name: "main", steps: &STEPS, entry: StepId(0) },
  ];

  pub static PROGRAM: Program<'static> = Program { tasks: &TASKS };
}
"#
}
