use serde::Deserialize;
use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR must be set"));
    fs::write(out_dir.join("memory.x"), include_bytes!("memory.x")).expect("write memory.x");
    println!("cargo:rustc-link-search={}", out_dir.display());
    println!("cargo:rerun-if-changed=memory.x");

    let manifest_dir =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR must be set"));
    let workspace_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .map(Path::to_path_buf)
        .unwrap_or_else(|| manifest_dir.clone());

    let generated_program_path = out_dir.join("generated_program.rs");
    println!("cargo:rerun-if-env-changed=RUST_PLC_GENERATED_PROGRAM_RS");
    match env::var("RUST_PLC_GENERATED_PROGRAM_RS") {
        Ok(path) => {
            let path = resolve_input_path(&workspace_root, &path);
            let contents = fs::read_to_string(&path).unwrap_or_else(|e| {
                panic!(
                    "failed to read RUST_PLC_GENERATED_PROGRAM_RS={}: {e}",
                    path.display()
                )
            });
            fs::write(&generated_program_path, contents).expect("write generated_program.rs");
        }
        Err(_) => {
            fs::write(&generated_program_path, default_generated_program())
                .expect("write default generated_program.rs");
        }
    }

    let scenario_rs_path = out_dir.join("scenario_data.rs");
    println!("cargo:rerun-if-env-changed=RUST_PLC_SCENARIO_YAML");
    match env::var("RUST_PLC_SCENARIO_YAML") {
        Ok(path) => {
            let path = resolve_input_path(&workspace_root, &path);
            let contents = fs::read_to_string(&path).unwrap_or_else(|e| {
                panic!(
                    "failed to read RUST_PLC_SCENARIO_YAML={}: {e}",
                    path.display()
                )
            });
            let scenario = parse_scenario(&contents);
            fs::write(&scenario_rs_path, render_scenario_rs(&scenario))
                .expect("write scenario_data.rs");
        }
        Err(_) => {
            fs::write(
                &scenario_rs_path,
                render_scenario_rs(&ScenarioData::default()),
            )
            .expect("write default scenario_data.rs");
        }
    }
}

fn resolve_input_path(workspace_root: &Path, raw: &str) -> PathBuf {
    let path = PathBuf::from(raw);
    if path.is_absolute() {
        path
    } else {
        workspace_root.join(path)
    }
}

#[derive(Debug, Clone, Deserialize, Default)]
struct ScenarioFile {
    #[serde(default)]
    tick_ms: u64,
    #[serde(default)]
    duration_ms: u64,
    #[serde(default)]
    inputs: Vec<InputEvent>,
}

#[derive(Debug, Clone, Deserialize)]
struct InputEvent {
    at_ms: u64,
    set: InputSet,
}

#[derive(Debug, Clone, Deserialize, Default)]
struct InputSet {
    #[serde(default)]
    digital_inputs: BTreeMap<u16, bool>,
    #[serde(default)]
    analog_inputs: BTreeMap<u16, f32>,
}

#[derive(Debug, Clone, Default)]
struct ScenarioData {
    tick_ms: u64,
    duration_ms: u64,
    digital_events: Vec<DigitalInputEvent>,
    analog_events: Vec<AnalogInputEvent>,
}

#[derive(Debug, Clone)]
struct DigitalInputEvent {
    at_tick: u64,
    id: u16,
    value: bool,
}

#[derive(Debug, Clone)]
struct AnalogInputEvent {
    at_tick: u64,
    id: u16,
    value: f32,
}

fn parse_scenario(yaml: &str) -> ScenarioData {
    let file: ScenarioFile =
        serde_yaml::from_str(yaml).unwrap_or_else(|e| panic!("invalid scenario yaml: {e}"));
    assert!(file.tick_ms > 0, "scenario tick_ms must be > 0");

    let mut out = ScenarioData {
        tick_ms: file.tick_ms,
        duration_ms: file.duration_ms,
        digital_events: Vec::new(),
        analog_events: Vec::new(),
    };
    for event in file.inputs {
        assert!(
            event.at_ms % file.tick_ms == 0,
            "scenario at_ms={} is not aligned to tick_ms={}",
            event.at_ms,
            file.tick_ms
        );
        let at_tick = event.at_ms / file.tick_ms;
        for (id, value) in event.set.digital_inputs {
            out.digital_events
                .push(DigitalInputEvent { at_tick, id, value });
        }
        for (id, value) in event.set.analog_inputs {
            out.analog_events
                .push(AnalogInputEvent { at_tick, id, value });
        }
    }
    out.digital_events.sort_by_key(|e| (e.at_tick, e.id));
    out.analog_events.sort_by_key(|e| (e.at_tick, e.id));
    out
}

fn render_scenario_rs(data: &ScenarioData) -> String {
    let mut out = String::new();
    out.push_str("// @generated by board-renode-stm32 build.rs\n");
    out.push_str("#[derive(Clone, Copy)]\n");
    out.push_str("pub struct DigitalInputEvent {\n");
    out.push_str("    pub at_tick: u64,\n");
    out.push_str("    pub id: u16,\n");
    out.push_str("    pub value: bool,\n");
    out.push_str("}\n");
    out.push_str("#[derive(Clone, Copy)]\n");
    out.push_str("pub struct AnalogInputEvent {\n");
    out.push_str("    pub at_tick: u64,\n");
    out.push_str("    pub id: u16,\n");
    out.push_str("    pub value: f32,\n");
    out.push_str("}\n");
    out.push_str(&format!("pub const TICK_MS: u64 = {};\n", data.tick_ms));
    out.push_str(&format!(
        "pub const DURATION_MS: u64 = {};\n",
        data.duration_ms
    ));
    out.push_str("pub const DIGITAL_INPUT_EVENTS: &[DigitalInputEvent] = &[\n");
    for event in &data.digital_events {
        out.push_str(&format!(
            "    DigitalInputEvent {{ at_tick: {}, id: {}, value: {} }},\n",
            event.at_tick, event.id, event.value
        ));
    }
    out.push_str("];\n");
    out.push_str("pub const ANALOG_INPUT_EVENTS: &[AnalogInputEvent] = &[\n");
    for event in &data.analog_events {
        out.push_str(&format!(
            "    AnalogInputEvent {{ at_tick: {}, id: {}, value: {:.6} }},\n",
            event.at_tick, event.id, event.value
        ));
    }
    out.push_str("];\n");
    out
}

fn default_generated_program() -> &'static str {
    r#"// @generated default board-renode-stm32 program
#[allow(clippy::all)]

pub mod generated {
  use runtime_core::{Instr, Program, Step, StepId, Task};

  static STEPS: [Step<'static>; 1] = [
    Step { name: "halt", instr: Instr::Halt },
  ];

  static TASKS: [Task<'static>; 1] = [
    Task { name: "main", steps: &STEPS, entry: StepId(0) },
  ];

  pub static PROGRAM: Program<'static> = Program { tasks: &TASKS, pid_loops: &[], var_init: &[], cam_configs: &[], cam_tables: &[], axis_fault_policies: &[], semantic_resources: &[], resource_claims: &[], workpiece_types: &[], workpiece_sites: &[], workpiece_holders: &[] };
}
"#
}
